@startuml
'https://plantuml.com/class-diagram
' CONVERT ICEPANEL DIAGRAM ===========
' Converter          : it.brunasti.icepanel.tools.IcePanelToPlantUmlConverter
' IcePanel JSON File : [./examples/ai/ARS-AI_Readiness_Survey.json]
' Configuration      : [./examples/ai/config.json]
' Generated at       : Thu May 02 18:03:09 CEST 2024

!include https://raw.githubusercontent.com/plantuml-stdlib/C4-PlantUML/master/C4_Context.puml
!include https://raw.githubusercontent.com/plantuml-stdlib/C4-PlantUML/master/C4_Component.puml



Component(5hrlGZy5caua0ihnw1fz, "AI Readiness Survey WebApp", "") { 
    ' CLASSES =======
    Container(VK9ZFiCYByBvFGzQxBpq, "Static Content", "", "")
    Container(SuPXys2m8MHNajNDAovG, "Security Component (FireWall...)", "", "")
    Container(x6BTWIQ3rThpdBgHOSRZ, "VueJS", "", "")
    Container(V9vsEFD13t044w0g9kcU, "Web Server", "", "")
}


' NEIGHBOR CLASSES =======
Person(3zCEc0A8nh1jzwekwJ9e, "User (Customer CEO)", "")
Component(mCLYSixzXMXK6M59oIYW, "API Gateway", "")


' SUB DIAGRAM CONNECTIONS ======= Base : [5hrlGZy5caua0ihnw1fz]
' CONNECTION : [Stores and reads] [d0yXDxJmyhA9EL5YiepF] [tlobGJ03gGg0eTGJjeCt] [bidirectional]
' CONNECTION : [Responds] [ccRXgtE4SCPOsJ86Bucd] [tkH0Nyiet0J81k3G0P0b] [outgoing]
' CONNECTION : [Utilises] [d0yXDxJmyhA9EL5YiepF] [VfVOeO3QyBIGXrvCOwIi] [outgoing]
' CONNECTION : [Uses] [bJilmQwJf6L105KZVIqf] [LS52GSxTaF82aLsMAGUJ] [outgoing]
' CONNECTION : [Composes] [tkH0Nyiet0J81k3G0P0b] [7eu55kM96LjjrzxMB2kO] [outgoing]
' CONNECTION : [Extracts] [tlobGJ03gGg0eTGJjeCt] [Zas67UmkOs1zk4BhDirK] [outgoing]
' CONNECTION : [Accesses] [d0yXDxJmyhA9EL5YiepF] [5eGbhrgZL6CVjXVxG9EB] [outgoing]
' CONNECTION : [Maintain] [aoPaRfmaQuiM5hH5QhmS] [3aSu0mcX7m60VrLzm7L6] [outgoing]
' CONNECTION : [User Survey Result] [4S6STeueefjDuU4xPjRW] [bJilmQwJf6L105KZVIqf] [outgoing]
' CONNECTION : [Compiles] [K4wE6hv7lp6PXCIzvmzi] [7eu55kM96LjjrzxMB2kO] [outgoing]
' CONNECTION : [Controls Access] [SuPXys2m8MHNajNDAovG] [V9vsEFD13t044w0g9kcU] [outgoing]
' Internal of (5hrlGZy5caua0ihnw1fz) (5hrlGZy5caua0ihnw1fz)
' both
Rel(SuPXys2m8MHNajNDAovG, V9vsEFD13t044w0g9kcU, "Controls Access" )
' CONNECTION : [Provides Contents] [6KEeGMtfXzcAtPxRMm95] [5eGbhrgZL6CVjXVxG9EB] [outgoing]
' CONNECTION : [Answered by] [K4wE6hv7lp6PXCIzvmzi] [bJilmQwJf6L105KZVIqf] [outgoing]
' CONNECTION : [Corresponds] [ccRXgtE4SCPOsJ86Bucd] [ToaUegZzOkTYIdKge5Qq] [outgoing]
' CONNECTION : [Updates] [I3ut2I4Ct9f3UDszgxf1] [iZVcQxlnkbrnOYjJqqv2] [outgoing]
' CONNECTION : [Delivers] [V9vsEFD13t044w0g9kcU] [VK9ZFiCYByBvFGzQxBpq] [outgoing]
' Internal of (5hrlGZy5caua0ihnw1fz) (5hrlGZy5caua0ihnw1fz)
' both
Rel(V9vsEFD13t044w0g9kcU, VK9ZFiCYByBvFGzQxBpq, "Delivers" )
' CONNECTION : [API Intreface] [x6BTWIQ3rThpdBgHOSRZ] [mCLYSixzXMXK6M59oIYW] [bidirectional]
' search target ancestor
' Target ancestor out of the container
Rel(x6BTWIQ3rThpdBgHOSRZ, mCLYSixzXMXK6M59oIYW, "API Intreface" )
Rel(mCLYSixzXMXK6M59oIYW, x6BTWIQ3rThpdBgHOSRZ, "Return of API Intreface" )
' CONNECTION : [Implemented by] [fhOu4B6mDXc7nf9z8b9C] [d0yXDxJmyhA9EL5YiepF] [outgoing]
' CONNECTION : [Provides I18N Content] [iZVcQxlnkbrnOYjJqqv2] [VfVOeO3QyBIGXrvCOwIi] [outgoing]
' CONNECTION : [Set Value for] [XrwLMmIqBRBHFCQBkwLC] [kqoiQoApomG9vCdJgRCS] [outgoing]
' CONNECTION : [Setups DB Structure] [aoPaRfmaQuiM5hH5QhmS] [tlobGJ03gGg0eTGJjeCt] [outgoing]
' CONNECTION : [Uses] [5hrlGZy5caua0ihnw1fz] [Fyh0CkKDWXU6cSuyq7FS] [outgoing]
' CONNECTION : [Refers to User] [XrwLMmIqBRBHFCQBkwLC] [bJilmQwJf6L105KZVIqf] [outgoing]
' CONNECTION : [Corresponds to Stage (Derived)] [LsUYohywFy73cbNxkS1m] [ToaUegZzOkTYIdKge5Qq] [outgoing]
' CONNECTION : [Commits code] [aoPaRfmaQuiM5hH5QhmS] [Fyh0CkKDWXU6cSuyq7FS] [outgoing]
' CONNECTION : [Publish] [mCLYSixzXMXK6M59oIYW] [3aSu0mcX7m60VrLzm7L6] [outgoing]
' CONNECTION : [Rappresents] [awiZhehg5tNZRyDuZDr9] [7eu55kM96LjjrzxMB2kO] [outgoing]
' CONNECTION : [Uses] [INwNu3tqXQVOUeQ95rmz] [Fyh0CkKDWXU6cSuyq7FS] [outgoing]
' CONNECTION : [Translates] [TxZtQCNHfOvU0hauU7me] [LS52GSxTaF82aLsMAGUJ] [outgoing]
' CONNECTION : [Dimension] [4S6STeueefjDuU4xPjRW] [awiZhehg5tNZRyDuZDr9] [outgoing]
' CONNECTION : [Sends Result] [I9erkX6JvcRx0uM4iieJ] [3zCEc0A8nh1jzwekwJ9e] [outgoing]
' CONNECTION : [Exposes Endpoints] [fhOu4B6mDXc7nf9z8b9C] [mCLYSixzXMXK6M59oIYW] [outgoing]
' CONNECTION : [Executes] [V9vsEFD13t044w0g9kcU] [x6BTWIQ3rThpdBgHOSRZ] [outgoing]
' Internal of (5hrlGZy5caua0ihnw1fz) (5hrlGZy5caua0ihnw1fz)
' both
Rel(V9vsEFD13t044w0g9kcU, x6BTWIQ3rThpdBgHOSRZ, "Executes" )
' CONNECTION : [status] [K4wE6hv7lp6PXCIzvmzi] [dOWFs1FDNaWOGsbJJUas] [outgoing]
' CONNECTION : [Reads data] [Q4JwBYUNizhrOK6IVNU0] [d0yXDxJmyhA9EL5YiepF] [outgoing]
' CONNECTION : [Uses] [SPQI7VF4lQr2xI6LfLFL] [Fyh0CkKDWXU6cSuyq7FS] [outgoing]
' CONNECTION : [Is Part Of] [tkH0Nyiet0J81k3G0P0b] [awiZhehg5tNZRyDuZDr9] [outgoing]
' CONNECTION : [Uses] [Zas67UmkOs1zk4BhDirK] [Fyh0CkKDWXU6cSuyq7FS] [outgoing]
' CONNECTION : [Reads report] [Zas67UmkOs1zk4BhDirK] [KkUEHQQOml7FBUrTDfgF] [outgoing]
' CONNECTION : [Refers to] [kqoiQoApomG9vCdJgRCS] [7eu55kM96LjjrzxMB2kO] [bidirectional]
' CONNECTION : [User Question Response] [LsUYohywFy73cbNxkS1m] [ccRXgtE4SCPOsJ86Bucd] [outgoing]
' CONNECTION : [Stored in] [iZVcQxlnkbrnOYjJqqv2] [tlobGJ03gGg0eTGJjeCt] [outgoing]
' CONNECTION : [Accesses] [3zCEc0A8nh1jzwekwJ9e] [SuPXys2m8MHNajNDAovG] [outgoing]
' search source ancestor
' Source ancestor out of the container
Rel(3zCEc0A8nh1jzwekwJ9e, SuPXys2m8MHNajNDAovG, "Accesses" )
' CONNECTION : [Requests sending of email] [Q4JwBYUNizhrOK6IVNU0] [I9erkX6JvcRx0uM4iieJ] [outgoing]
' CONNECTION : [Provide Sources] [Fyh0CkKDWXU6cSuyq7FS] [MVsaKWytzsPec5DvAzrJ] [outgoing]


@enduml
