@startuml
'https://plantuml.com/class-diagram
' CONVERT ICEPANEL DIAGRAM ===========
' Converter          : it.brunasti.icepanel.tools.IcePanelToPlantUmlConverter
' IcePanel JSON File : [./examples/ai/ARS-AI_Readiness_Survey.json]
' Configuration      : [./examples/ai/config.json]
' Generated at       : Mon May 13 16:35:34 CEST 2024

!include https://raw.githubusercontent.com/plantuml-stdlib/C4-PlantUML/master/C4_Context.puml
!include https://raw.githubusercontent.com/plantuml-stdlib/C4-PlantUML/master/C4_Component.puml



Component(SPQI7VF4lQr2xI6LfLFL, "AI Readiness Survey BE", "") { 
    ' CLASSES =======
    Container(VfVOeO3QyBIGXrvCOwIi, "I18N System", "", "")
    Container(5eGbhrgZL6CVjXVxG9EB, "CRM System", "", "")
    Container(fhOu4B6mDXc7nf9z8b9C, "AWS API Gateway", "", "")
    Container(d0yXDxJmyhA9EL5YiepF, "BE Application", "", "")
}


' NEIGHBOR CLASSES =======
ContainerDb(iZVcQxlnkbrnOYjJqqv2, "Dynamic I18N Content", "", "")
ContainerDb(6KEeGMtfXzcAtPxRMm95, "CRM Contents", "", "")
Container(Q4JwBYUNizhrOK6IVNU0, "Integration System", "", "")
Component(mCLYSixzXMXK6M59oIYW, "API Gateway", "")
ContainerDb(tlobGJ03gGg0eTGJjeCt, "AI Readiness Survey Storage", "", "")


' SUB DIAGRAM CONNECTIONS ======= Base : [SPQI7VF4lQr2xI6LfLFL]
' CONNECTION : [Stores and reads] [d0yXDxJmyhA9EL5YiepF] [tlobGJ03gGg0eTGJjeCt] [bidirectional]
Rel(d0yXDxJmyhA9EL5YiepF, tlobGJ03gGg0eTGJjeCt, "Stores and reads" )
Rel(tlobGJ03gGg0eTGJjeCt, d0yXDxJmyhA9EL5YiepF, "Return of Stores and reads" )
' CONNECTION : [Utilises] [d0yXDxJmyhA9EL5YiepF] [VfVOeO3QyBIGXrvCOwIi] [outgoing]
Rel(d0yXDxJmyhA9EL5YiepF, VfVOeO3QyBIGXrvCOwIi, "Utilises" )
' CONNECTION : [Accesses] [d0yXDxJmyhA9EL5YiepF] [5eGbhrgZL6CVjXVxG9EB] [outgoing]
Rel(d0yXDxJmyhA9EL5YiepF, 5eGbhrgZL6CVjXVxG9EB, "Accesses" )
' CONNECTION : [Provides Contents] [6KEeGMtfXzcAtPxRMm95] [5eGbhrgZL6CVjXVxG9EB] [outgoing]
Rel(6KEeGMtfXzcAtPxRMm95, 5eGbhrgZL6CVjXVxG9EB, "Provides Contents" )
' CONNECTION : [Implemented by] [fhOu4B6mDXc7nf9z8b9C] [d0yXDxJmyhA9EL5YiepF] [outgoing]
Rel(fhOu4B6mDXc7nf9z8b9C, d0yXDxJmyhA9EL5YiepF, "Implemented by" )
' CONNECTION : [Provides I18N Content] [iZVcQxlnkbrnOYjJqqv2] [VfVOeO3QyBIGXrvCOwIi] [outgoing]
Rel(iZVcQxlnkbrnOYjJqqv2, VfVOeO3QyBIGXrvCOwIi, "Provides I18N Content" )
' CONNECTION : [Exposes Endpoints] [fhOu4B6mDXc7nf9z8b9C] [mCLYSixzXMXK6M59oIYW] [outgoing]
Rel(fhOu4B6mDXc7nf9z8b9C, mCLYSixzXMXK6M59oIYW, "Exposes Endpoints" )
' CONNECTION : [Reads data] [Q4JwBYUNizhrOK6IVNU0] [d0yXDxJmyhA9EL5YiepF] [outgoing]
Rel(Q4JwBYUNizhrOK6IVNU0, d0yXDxJmyhA9EL5YiepF, "Reads data" )


@enduml
