@startuml
'https://plantuml.com/class-diagram
' CONVERT ICEPANEL DIAGRAM ===========
' Converter          : it.brunasti.icepanel.tools.IcePanelToPlantUmlConverter
' IcePanel JSON File : [./examples/ai/ARS-AI_Readiness_Survey.json]
' Configuration      : [./examples/ai/config.json]
' Generated at       : Thu May 02 18:27:59 CEST 2024

!include https://raw.githubusercontent.com/plantuml-stdlib/C4-PlantUML/master/C4_Context.puml
!include https://raw.githubusercontent.com/plantuml-stdlib/C4-PlantUML/master/C4_Component.puml



System_Boundary(DTAvEftAPfnuVbWeBkJO, "Git Repo" ) {
    ' CLASSES =======
    ContainerDb(Fyh0CkKDWXU6cSuyq7FS, "GitHub Repo System", "", "")
}


' NEIGHBOR CLASSES =======
Component(5hrlGZy5caua0ihnw1fz, "AI Readiness Survey WebApp", "")
Component(INwNu3tqXQVOUeQ95rmz, "Notification System", "")
Person(aoPaRfmaQuiM5hH5QhmS, "AND Developer", "")
Component(Zas67UmkOs1zk4BhDirK, "Reporting System", "")
Component(SPQI7VF4lQr2xI6LfLFL, "AI Readiness Survey BE", "")
System(MVsaKWytzsPec5DvAzrJ, "AI Readiness Survey Application", "Enable the AI Readiness Survey")


' SUB DIAGRAM CONNECTIONS ======= Base : [DTAvEftAPfnuVbWeBkJO]
' CONNECTION : [Uses] [5hrlGZy5caua0ihnw1fz] [Fyh0CkKDWXU6cSuyq7FS] [outgoing]
Rel(5hrlGZy5caua0ihnw1fz, Fyh0CkKDWXU6cSuyq7FS, "Uses" )
' CONNECTION : [Commits code] [aoPaRfmaQuiM5hH5QhmS] [Fyh0CkKDWXU6cSuyq7FS] [outgoing]
Rel(aoPaRfmaQuiM5hH5QhmS, Fyh0CkKDWXU6cSuyq7FS, "Commits code" )
' CONNECTION : [Uses] [INwNu3tqXQVOUeQ95rmz] [Fyh0CkKDWXU6cSuyq7FS] [outgoing]
Rel(INwNu3tqXQVOUeQ95rmz, Fyh0CkKDWXU6cSuyq7FS, "Uses" )
' CONNECTION : [Uses] [SPQI7VF4lQr2xI6LfLFL] [Fyh0CkKDWXU6cSuyq7FS] [outgoing]
Rel(SPQI7VF4lQr2xI6LfLFL, Fyh0CkKDWXU6cSuyq7FS, "Uses" )
' CONNECTION : [Uses] [Zas67UmkOs1zk4BhDirK] [Fyh0CkKDWXU6cSuyq7FS] [outgoing]
Rel(Zas67UmkOs1zk4BhDirK, Fyh0CkKDWXU6cSuyq7FS, "Uses" )
' CONNECTION : [Provide Sources] [Fyh0CkKDWXU6cSuyq7FS] [MVsaKWytzsPec5DvAzrJ] [outgoing]
Rel(Fyh0CkKDWXU6cSuyq7FS, MVsaKWytzsPec5DvAzrJ, "Provide Sources" )


@enduml
