@startuml
'https://plantuml.com/class-diagram
' CONVERT ICEPANEL DIAGRAM ===========
' Converter          : it.brunasti.icepanel.tools.IcePanelToPlantUmlConverter
' IcePanel JSON File : [./examples/ai/ARS-AI_Readiness_Survey.json]
' Configuration      : [./examples/ai/config.json]
' Generated at       : Thu May 02 18:27:59 CEST 2024

!include https://raw.githubusercontent.com/plantuml-stdlib/C4-PlantUML/master/C4_Context.puml
!include https://raw.githubusercontent.com/plantuml-stdlib/C4-PlantUML/master/C4_Component.puml



    ' CLASSES =======
    Container(ccRXgtE4SCPOsJ86Bucd, "Question Option", "", "")
    Container(kqoiQoApomG9vCdJgRCS, "Demographic Dimension", "", "")
    Container(dOWFs1FDNaWOGsbJJUas, "Survey Status", "", "")
    Container(TxZtQCNHfOvU0hauU7me, "I18N Translation", "", "")
    Container(awiZhehg5tNZRyDuZDr9, "Survey Dimension", "", "")
    Container(K4wE6hv7lp6PXCIzvmzi, "User Survey Rel", "", "")
    Container(LsUYohywFy73cbNxkS1m, "User Response", "", "")
    Container(tkH0Nyiet0J81k3G0P0b, "Survey Question", "", "")
    Container(XrwLMmIqBRBHFCQBkwLC, "User Demografic Value", "", "")
    Container(bJilmQwJf6L105KZVIqf, "User", "", "")
    Container(LS52GSxTaF82aLsMAGUJ, "Language", "", "")
    Container(7eu55kM96LjjrzxMB2kO, "Survey (Assessment)", "", "")
    Container(4S6STeueefjDuU4xPjRW, "User Dimentsion Value", "", "")
    Container(ToaUegZzOkTYIdKge5Qq, "Stage", "", "")
}


' NEIGHBOR CLASSES =======


' SUB DIAGRAM CONNECTIONS ======= Base : [tlobGJ03gGg0eTGJjeCt]
' CONNECTION : [Responds] [ccRXgtE4SCPOsJ86Bucd] [tkH0Nyiet0J81k3G0P0b] [outgoing]
Rel(ccRXgtE4SCPOsJ86Bucd, tkH0Nyiet0J81k3G0P0b, "Responds" )
' CONNECTION : [Uses] [bJilmQwJf6L105KZVIqf] [LS52GSxTaF82aLsMAGUJ] [outgoing]
Rel(bJilmQwJf6L105KZVIqf, LS52GSxTaF82aLsMAGUJ, "Uses" )
' CONNECTION : [Composes] [tkH0Nyiet0J81k3G0P0b] [7eu55kM96LjjrzxMB2kO] [outgoing]
Rel(tkH0Nyiet0J81k3G0P0b, 7eu55kM96LjjrzxMB2kO, "Composes" )
' CONNECTION : [User Survey Result] [4S6STeueefjDuU4xPjRW] [bJilmQwJf6L105KZVIqf] [outgoing]
Rel(4S6STeueefjDuU4xPjRW, bJilmQwJf6L105KZVIqf, "User Survey Result" )
' CONNECTION : [Compiles] [K4wE6hv7lp6PXCIzvmzi] [7eu55kM96LjjrzxMB2kO] [outgoing]
Rel(K4wE6hv7lp6PXCIzvmzi, 7eu55kM96LjjrzxMB2kO, "Compiles" )
' CONNECTION : [Answered by] [K4wE6hv7lp6PXCIzvmzi] [bJilmQwJf6L105KZVIqf] [outgoing]
Rel(K4wE6hv7lp6PXCIzvmzi, bJilmQwJf6L105KZVIqf, "Answered by" )
' CONNECTION : [Corresponds] [ccRXgtE4SCPOsJ86Bucd] [ToaUegZzOkTYIdKge5Qq] [outgoing]
Rel(ccRXgtE4SCPOsJ86Bucd, ToaUegZzOkTYIdKge5Qq, "Corresponds" )
' CONNECTION : [Set Value for] [XrwLMmIqBRBHFCQBkwLC] [kqoiQoApomG9vCdJgRCS] [outgoing]
Rel(XrwLMmIqBRBHFCQBkwLC, kqoiQoApomG9vCdJgRCS, "Set Value for" )
' CONNECTION : [Refers to User] [XrwLMmIqBRBHFCQBkwLC] [bJilmQwJf6L105KZVIqf] [outgoing]
Rel(XrwLMmIqBRBHFCQBkwLC, bJilmQwJf6L105KZVIqf, "Refers to User" )
' CONNECTION : [Corresponds to Stage (Derived)] [LsUYohywFy73cbNxkS1m] [ToaUegZzOkTYIdKge5Qq] [outgoing]
Rel(LsUYohywFy73cbNxkS1m, ToaUegZzOkTYIdKge5Qq, "Corresponds to Stage (Derived)" )
' CONNECTION : [Rappresents] [awiZhehg5tNZRyDuZDr9] [7eu55kM96LjjrzxMB2kO] [outgoing]
Rel(awiZhehg5tNZRyDuZDr9, 7eu55kM96LjjrzxMB2kO, "Rappresents" )
' CONNECTION : [Translates] [TxZtQCNHfOvU0hauU7me] [LS52GSxTaF82aLsMAGUJ] [outgoing]
Rel(TxZtQCNHfOvU0hauU7me, LS52GSxTaF82aLsMAGUJ, "Translates" )
' CONNECTION : [Dimension] [4S6STeueefjDuU4xPjRW] [awiZhehg5tNZRyDuZDr9] [outgoing]
Rel(4S6STeueefjDuU4xPjRW, awiZhehg5tNZRyDuZDr9, "Dimension" )
' CONNECTION : [status] [K4wE6hv7lp6PXCIzvmzi] [dOWFs1FDNaWOGsbJJUas] [outgoing]
Rel(K4wE6hv7lp6PXCIzvmzi, dOWFs1FDNaWOGsbJJUas, "status" )
' CONNECTION : [Is Part Of] [tkH0Nyiet0J81k3G0P0b] [awiZhehg5tNZRyDuZDr9] [outgoing]
Rel(tkH0Nyiet0J81k3G0P0b, awiZhehg5tNZRyDuZDr9, "Is Part Of" )
' CONNECTION : [Refers to] [kqoiQoApomG9vCdJgRCS] [7eu55kM96LjjrzxMB2kO] [bidirectional]
Rel(kqoiQoApomG9vCdJgRCS, 7eu55kM96LjjrzxMB2kO, "Refers to" )
Rel(7eu55kM96LjjrzxMB2kO, kqoiQoApomG9vCdJgRCS, "Return of Refers to" )
' CONNECTION : [User Question Response] [LsUYohywFy73cbNxkS1m] [ccRXgtE4SCPOsJ86Bucd] [outgoing]
Rel(LsUYohywFy73cbNxkS1m, ccRXgtE4SCPOsJ86Bucd, "User Question Response" )


@enduml
