@startuml
'https://plantuml.com/class-diagram
' CONVERT ICEPANEL DIAGRAM ===========
' Converter          : it.brunasti.icepanel.tools.IcePanelToPlantUmlConverter
' IcePanel JSON File : [./examples/ai/ARS-AI_Readiness_Survey.json]
' Configuration      : [./examples/ai/config.json]
' Generated at       : Thu May 02 18:27:59 CEST 2024

!include https://raw.githubusercontent.com/plantuml-stdlib/C4-PlantUML/master/C4_Context.puml
!include https://raw.githubusercontent.com/plantuml-stdlib/C4-PlantUML/master/C4_Component.puml



Component(5hrlGZy5caua0ihnw1fz, "AI Readiness Survey WebApp", "") { 
    ' CLASSES =======
    Container(VK9ZFiCYByBvFGzQxBpq, "Static Content", "", "")
    Container(SuPXys2m8MHNajNDAovG, "Security Component (FireWall...)", "", "")
    Container(x6BTWIQ3rThpdBgHOSRZ, "VueJS", "", "")
    Container(V9vsEFD13t044w0g9kcU, "Web Server", "", "")
}


' NEIGHBOR CLASSES =======
Person(3zCEc0A8nh1jzwekwJ9e, "User (Customer CEO)", "")
Component(mCLYSixzXMXK6M59oIYW, "API Gateway", "")


' SUB DIAGRAM CONNECTIONS ======= Base : [5hrlGZy5caua0ihnw1fz]
' CONNECTION : [Controls Access] [SuPXys2m8MHNajNDAovG] [V9vsEFD13t044w0g9kcU] [outgoing]
Rel(SuPXys2m8MHNajNDAovG, V9vsEFD13t044w0g9kcU, "Controls Access" )
' CONNECTION : [Delivers] [V9vsEFD13t044w0g9kcU] [VK9ZFiCYByBvFGzQxBpq] [outgoing]
Rel(V9vsEFD13t044w0g9kcU, VK9ZFiCYByBvFGzQxBpq, "Delivers" )
' CONNECTION : [API Intreface] [x6BTWIQ3rThpdBgHOSRZ] [mCLYSixzXMXK6M59oIYW] [bidirectional]
Rel(x6BTWIQ3rThpdBgHOSRZ, mCLYSixzXMXK6M59oIYW, "API Intreface" )
Rel(mCLYSixzXMXK6M59oIYW, x6BTWIQ3rThpdBgHOSRZ, "Return of API Intreface" )
' CONNECTION : [Executes] [V9vsEFD13t044w0g9kcU] [x6BTWIQ3rThpdBgHOSRZ] [outgoing]
Rel(V9vsEFD13t044w0g9kcU, x6BTWIQ3rThpdBgHOSRZ, "Executes" )
' CONNECTION : [Accesses] [3zCEc0A8nh1jzwekwJ9e] [SuPXys2m8MHNajNDAovG] [outgoing]
Rel(3zCEc0A8nh1jzwekwJ9e, SuPXys2m8MHNajNDAovG, "Accesses" )


@enduml
