@startuml
'https://plantuml.com/class-diagram
' CONVERT ICEPANEL DIAGRAM ===========
' Converter          : it.brunasti.icepanel.tools.IcePanelToPlantUmlConverter
' IcePanel JSON File : [./examples/ai/ARS-AI_Readiness_Survey.json]
' Configuration      : [./examples/ai/config.json]
' Generated at       : Thu May 02 18:27:59 CEST 2024

!include https://raw.githubusercontent.com/plantuml-stdlib/C4-PlantUML/master/C4_Context.puml
!include https://raw.githubusercontent.com/plantuml-stdlib/C4-PlantUML/master/C4_Component.puml



System_Boundary(MVsaKWytzsPec5DvAzrJ, "AI Readiness Survey Application" ) {
    ' CLASSES =======
    Component(Zas67UmkOs1zk4BhDirK, "Reporting System", "")
    Component(mCLYSixzXMXK6M59oIYW, "API Gateway", "")
    Component(5hrlGZy5caua0ihnw1fz, "AI Readiness Survey WebApp", "")
    ContainerDb(iZVcQxlnkbrnOYjJqqv2, "Dynamic I18N Content", "", "")
    ContainerDb(6KEeGMtfXzcAtPxRMm95, "CRM Contents", "", "")
    Component(3aSu0mcX7m60VrLzm7L6, "OpenAPI Doc", "")
    Component(SPQI7VF4lQr2xI6LfLFL, "AI Readiness Survey BE", "")
    Component(INwNu3tqXQVOUeQ95rmz, "Notification System", "")
    ContainerDb(tlobGJ03gGg0eTGJjeCt, "AI Readiness Survey Storage", "", "")
}


' NEIGHBOR CLASSES =======
Person(aoPaRfmaQuiM5hH5QhmS, "AND Developer", "")
Person(I3ut2I4Ct9f3UDszgxf1, "Translator", "")
Person(KkUEHQQOml7FBUrTDfgF, "AND User", "")
Person(3zCEc0A8nh1jzwekwJ9e, "User (Customer CEO)", "")
ContainerDb(Fyh0CkKDWXU6cSuyq7FS, "GitHub Repo System", "", "")


' SUB DIAGRAM CONNECTIONS ======= Base : [MVsaKWytzsPec5DvAzrJ]
' CONNECTION : [Stores and reads] [SPQI7VF4lQr2xI6LfLFL] [tlobGJ03gGg0eTGJjeCt] [bidirectional]
Rel(SPQI7VF4lQr2xI6LfLFL, tlobGJ03gGg0eTGJjeCt, "Stores and reads" )
Rel(tlobGJ03gGg0eTGJjeCt, SPQI7VF4lQr2xI6LfLFL, "Return of Stores and reads" )
' CONNECTION : [Extracts] [tlobGJ03gGg0eTGJjeCt] [Zas67UmkOs1zk4BhDirK] [outgoing]
Rel(tlobGJ03gGg0eTGJjeCt, Zas67UmkOs1zk4BhDirK, "Extracts" )
' CONNECTION : [Maintain] [aoPaRfmaQuiM5hH5QhmS] [3aSu0mcX7m60VrLzm7L6] [outgoing]
Rel(aoPaRfmaQuiM5hH5QhmS, 3aSu0mcX7m60VrLzm7L6, "Maintain" )
' CONNECTION : [Provides Contents] [6KEeGMtfXzcAtPxRMm95] [SPQI7VF4lQr2xI6LfLFL] [outgoing]
Rel(6KEeGMtfXzcAtPxRMm95, SPQI7VF4lQr2xI6LfLFL, "Provides Contents" )
' CONNECTION : [Updates] [I3ut2I4Ct9f3UDszgxf1] [iZVcQxlnkbrnOYjJqqv2] [outgoing]
Rel(I3ut2I4Ct9f3UDszgxf1, iZVcQxlnkbrnOYjJqqv2, "Updates" )
' CONNECTION : [API Intreface] [5hrlGZy5caua0ihnw1fz] [mCLYSixzXMXK6M59oIYW] [bidirectional]
Rel(5hrlGZy5caua0ihnw1fz, mCLYSixzXMXK6M59oIYW, "API Intreface" )
Rel(mCLYSixzXMXK6M59oIYW, 5hrlGZy5caua0ihnw1fz, "Return of API Intreface" )
' CONNECTION : [Provides I18N Content] [iZVcQxlnkbrnOYjJqqv2] [SPQI7VF4lQr2xI6LfLFL] [outgoing]
Rel(iZVcQxlnkbrnOYjJqqv2, SPQI7VF4lQr2xI6LfLFL, "Provides I18N Content" )
' CONNECTION : [Setups DB Structure] [aoPaRfmaQuiM5hH5QhmS] [tlobGJ03gGg0eTGJjeCt] [outgoing]
Rel(aoPaRfmaQuiM5hH5QhmS, tlobGJ03gGg0eTGJjeCt, "Setups DB Structure" )
' CONNECTION : [Uses] [5hrlGZy5caua0ihnw1fz] [Fyh0CkKDWXU6cSuyq7FS] [outgoing]
Rel(5hrlGZy5caua0ihnw1fz, Fyh0CkKDWXU6cSuyq7FS, "Uses" )
' CONNECTION : [Publish] [mCLYSixzXMXK6M59oIYW] [3aSu0mcX7m60VrLzm7L6] [outgoing]
Rel(mCLYSixzXMXK6M59oIYW, 3aSu0mcX7m60VrLzm7L6, "Publish" )
' CONNECTION : [Uses] [INwNu3tqXQVOUeQ95rmz] [Fyh0CkKDWXU6cSuyq7FS] [outgoing]
Rel(INwNu3tqXQVOUeQ95rmz, Fyh0CkKDWXU6cSuyq7FS, "Uses" )
' CONNECTION : [Sends Result] [INwNu3tqXQVOUeQ95rmz] [3zCEc0A8nh1jzwekwJ9e] [outgoing]
Rel(INwNu3tqXQVOUeQ95rmz, 3zCEc0A8nh1jzwekwJ9e, "Sends Result" )
' CONNECTION : [Exposes Endpoints] [SPQI7VF4lQr2xI6LfLFL] [mCLYSixzXMXK6M59oIYW] [outgoing]
Rel(SPQI7VF4lQr2xI6LfLFL, mCLYSixzXMXK6M59oIYW, "Exposes Endpoints" )
' CONNECTION : [Reads data] [INwNu3tqXQVOUeQ95rmz] [SPQI7VF4lQr2xI6LfLFL] [outgoing]
Rel(INwNu3tqXQVOUeQ95rmz, SPQI7VF4lQr2xI6LfLFL, "Reads data" )
' CONNECTION : [Uses] [SPQI7VF4lQr2xI6LfLFL] [Fyh0CkKDWXU6cSuyq7FS] [outgoing]
Rel(SPQI7VF4lQr2xI6LfLFL, Fyh0CkKDWXU6cSuyq7FS, "Uses" )
' CONNECTION : [Uses] [Zas67UmkOs1zk4BhDirK] [Fyh0CkKDWXU6cSuyq7FS] [outgoing]
Rel(Zas67UmkOs1zk4BhDirK, Fyh0CkKDWXU6cSuyq7FS, "Uses" )
' CONNECTION : [Reads report] [Zas67UmkOs1zk4BhDirK] [KkUEHQQOml7FBUrTDfgF] [outgoing]
Rel(Zas67UmkOs1zk4BhDirK, KkUEHQQOml7FBUrTDfgF, "Reads report" )
' CONNECTION : [Stored in] [iZVcQxlnkbrnOYjJqqv2] [tlobGJ03gGg0eTGJjeCt] [outgoing]
Rel(iZVcQxlnkbrnOYjJqqv2, tlobGJ03gGg0eTGJjeCt, "Stored in" )
' CONNECTION : [Accesses] [3zCEc0A8nh1jzwekwJ9e] [5hrlGZy5caua0ihnw1fz] [outgoing]
Rel(3zCEc0A8nh1jzwekwJ9e, 5hrlGZy5caua0ihnw1fz, "Accesses" )


@enduml
