@startuml
'https://plantuml.com/class-diagram
' CONVERT ICEPANEL DIAGRAM ===========
' Converter          : it.brunasti.icepanel.tools.IcePanelToPlantUmlConverter
' IcePanel JSON File : [./examples/ai/ARS-AI_Readiness_Survey.json]
' Configuration      : [./examples/ai/config.json]
' Generated at       : Wed May 01 15:06:54 CEST 2024

!include https://raw.githubusercontent.com/plantuml-stdlib/C4-PlantUML/master/C4_Context.puml
!include https://raw.githubusercontent.com/plantuml-stdlib/C4-PlantUML/master/C4_Component.puml



    ' CLASSES =======
    Container(ccRXgtE4SCPOsJ86Bucd, "Question Option", "", "")
    Container(kqoiQoApomG9vCdJgRCS, "Demographic Dimension", "", "")
    Container(dOWFs1FDNaWOGsbJJUas, "Survey Status", "", "")
    Container(TxZtQCNHfOvU0hauU7me, "I18N Translation", "", "")
    Container(awiZhehg5tNZRyDuZDr9, "Survey Dimension", "", "")
    Container(K4wE6hv7lp6PXCIzvmzi, "User Survey Rel", "", "")
    Container(LsUYohywFy73cbNxkS1m, "User Response", "", "")
    Container(tkH0Nyiet0J81k3G0P0b, "Survey Question", "", "")
    Container(XrwLMmIqBRBHFCQBkwLC, "User Demografic Value", "", "")
    Container(bJilmQwJf6L105KZVIqf, "User", "", "")
    Container(LS52GSxTaF82aLsMAGUJ, "Language", "", "")
    Container(7eu55kM96LjjrzxMB2kO, "Survey (Assessment)", "", "")
    Container(4S6STeueefjDuU4xPjRW, "User Dimentsion Value", "", "")
    Container(ToaUegZzOkTYIdKge5Qq, "Stage", "", "")
}


' NEIGHBOR CLASSES =======


' CONNECTIONS =======
Rel(ccRXgtE4SCPOsJ86Bucd, tkH0Nyiet0J81k3G0P0b, "Responds" )
Rel(bJilmQwJf6L105KZVIqf, LS52GSxTaF82aLsMAGUJ, "Uses" )
Rel(tkH0Nyiet0J81k3G0P0b, 7eu55kM96LjjrzxMB2kO, "Composes" )
Rel(4S6STeueefjDuU4xPjRW, bJilmQwJf6L105KZVIqf, "User Survey Result" )
Rel(K4wE6hv7lp6PXCIzvmzi, 7eu55kM96LjjrzxMB2kO, "Compiles" )
Rel(K4wE6hv7lp6PXCIzvmzi, bJilmQwJf6L105KZVIqf, "Answered by" )
Rel(ccRXgtE4SCPOsJ86Bucd, ToaUegZzOkTYIdKge5Qq, "Corresponds" )
Rel(XrwLMmIqBRBHFCQBkwLC, kqoiQoApomG9vCdJgRCS, "Set Value for" )
Rel(XrwLMmIqBRBHFCQBkwLC, bJilmQwJf6L105KZVIqf, "Refers to User" )
Rel(LsUYohywFy73cbNxkS1m, ToaUegZzOkTYIdKge5Qq, "Corresponds to Stage (Derived)" )
Rel(awiZhehg5tNZRyDuZDr9, 7eu55kM96LjjrzxMB2kO, "Rappresents" )
Rel(TxZtQCNHfOvU0hauU7me, LS52GSxTaF82aLsMAGUJ, "Translates" )
Rel(4S6STeueefjDuU4xPjRW, awiZhehg5tNZRyDuZDr9, "Dimension" )
Rel(K4wE6hv7lp6PXCIzvmzi, dOWFs1FDNaWOGsbJJUas, "status" )
Rel(tkH0Nyiet0J81k3G0P0b, awiZhehg5tNZRyDuZDr9, "Is Part Of" )
Rel(kqoiQoApomG9vCdJgRCS, 7eu55kM96LjjrzxMB2kO, "Refers to" )
Rel(7eu55kM96LjjrzxMB2kO, kqoiQoApomG9vCdJgRCS, "Return of Refers to" )
Rel(LsUYohywFy73cbNxkS1m, ccRXgtE4SCPOsJ86Bucd, "User Question Response" )


@enduml
