@startuml
'https://plantuml.com/class-diagram
' CONVERT ICEPANEL DIAGRAM ===========
' Converter          : it.brunasti.icepanel.tools.IcePanelToPlantUMLConverter
' IcePanel JSON File : [./examples/pg/pg-001.json]
' Configuration      : [./examples/pg/config.json]
' Generated at       : Mon Apr 08 14:04:31 CEST 2024

!include https://raw.githubusercontent.com/plantuml-stdlib/C4-PlantUML/master/C4_Context.puml
!include https://raw.githubusercontent.com/plantuml-stdlib/C4-PlantUML/master/C4_Component.puml



System_Boundary(Dh7TjqtXo9JVsCCn3bol, "POS" ) {
    ' CLASSES =======
    ContainerDb(NnTsKEkdWpfDh4c5RyvC, "Local DB", "null", "" )
    Component(q8mphiB74ORpViZtWerc, "Card Reader", "null" )
    Component(dB0dSFz9vWxK3sHTYoeN, "Ms Dynamics", "null" )
    Component(aqahI4H2TS1bek5eriv4, "Clerk Console", "null" )
}


' NEIGHBOR CLASSES =======
System(soKzn6Drl9ZnctLZPvDw, "Finance System", "null" )


' CONNECTIONS =======
Rel(aqahI4H2TS1bek5eriv4, q8mphiB74ORpViZtWerc, "Start Payment" )
Rel(q8mphiB74ORpViZtWerc, aqahI4H2TS1bek5eriv4, "Return of Start Payment" )
Rel(dB0dSFz9vWxK3sHTYoeN, soKzn6Drl9ZnctLZPvDw, "Transmission every 30 minutes" )


@enduml
