@startuml
'https://plantuml.com/class-diagram
' CONVERT ICEPANEL DIAGRAM ===========
' Converter          : it.brunasti.icepanel.tools.IcePanelToPlantUmlConverter
' IcePanel JSON File : [./examples/pg/pg-001.json]
' Configuration      : [./examples/pg/config.json]
' Generated at       : Sun Dec 29 18:49:47 CET 2024

!include https://raw.githubusercontent.com/plantuml-stdlib/C4-PlantUML/master/C4_Context.puml
!include https://raw.githubusercontent.com/plantuml-stdlib/C4-PlantUML/master/C4_Component.puml



System_Boundary(88WfRG0t8ypOt3D9tEdU, "" ) {
    ' CLASSES =======
    Person(FBBbTGT0oOXfeMyhwVyC, "Sompop Khamchoo", "")
    Person(KpYA4jfUm7DneGIwDLve, "Jake Rostron", "")
    Person(QZlQ9DNfCiQS6jQoJxej, "Jodie Whitter", "")
    Person(8jNpTltrLLDgEn6uCl8w, "Frederik Rasch Madsen", "")
    Person(I9HRSQxIrrm3rr7LJ5jb, "Aleksandra Wyrwich ", "")
    Person(nCNagrErDOB3JMDOzS6m, "Daryl Watts", "")
    Person(4YBP6BlFzBp8pOuJwQQE, "Lakshmana Davisetti", "")
    Person(LV2WD5SPjO4cbOAOnQ3R, "Jordan Woodley", "")
    Person(NaJIADIPPqioEnMsZKFv, "Paolo", "")
    Person(tqwJyVeVwbC3aj0tpKJH, "James Keiller", "")
    Person(ocSPSt7sJwv7vL7dW0Wu, "Tom Bitter ", "")
    Person(1wd6WWhc36tXZPDMAHGd, "Jacob Schaltz", "")
    Person(FsyGpvOu3nIbx1y3FFwf, "Dan Jones", "")
    Person(nsHGSpPSB65xQVEo95eL, "Andy Caddy", "")
    Person(PQmlX7q91Kh3Yf0F3HKA, "Martin Neble Green", "")
    Person(30kdN3ZfUiaC147oEUgD, "Jack", "")
    Person(xvtSOwqgkJuiS1AUfHtq, "Stefanie Fässler", "")
    Person(gyFaqXTUHNWi35U8x75B, "Ellen Robinson ", "")
    Person(lzhQlWw0cvbzHdfNSybV, "Torben Torndahl Madsen ", "")
    Person(xG1SdOSA0DNgOQpu3sQf, "ex Fabian Eberle", "")
    Person(xAUvR8Pfbnu2Rdl1PxL0, "Anders", "")
    Person(Z4bU5pNQCdeeNEnA1ez2, "Flemming", "")
    Person(bXWevRXRAy4B5zBAHrcI, "Graham Sundman", "")
    Person(yxSolsmKtSMWI2da2IaD, "John Thixton", "")
    Person(VHvtx6bRzcO3NXYLpZD8, "Allan Alexander", "")
    Person(g1cGlwqdjoOmA7N5PpxG, "Florian Stern ", "")
    Person(AMArsaUOgqE6KskBetpH, "Lee", "")
    Person(Gl98BoHAVzjhoEfzW22z, "Luca Kyburz", "")
    Person(pQdt7xK7tyooOlXDp01L, "Carl Stokes", "")
    Person(5gELAvR5vUNER5UJDdEo, "Laura Cross", "")
}


' NEIGHBOR CLASSES =======


' SUB DIAGRAM CONNECTIONS ======= Base : [88WfRG0t8ypOt3D9tEdU]


@enduml
