@startuml
'https://plantuml.com/class-diagram
' CONVERT ICEPANEL DIAGRAM ===========
' Converter          : it.brunasti.icepanel.tools.IcePanelToPlantUmlConverter
' IcePanel JSON File : [./examples/pg/pg-001.json]
' Configuration      : [./examples/pg/config.json]
' Generated at       : Sun Dec 29 18:49:47 CET 2024

!include https://raw.githubusercontent.com/plantuml-stdlib/C4-PlantUML/master/C4_Context.puml
!include https://raw.githubusercontent.com/plantuml-stdlib/C4-PlantUML/master/C4_Component.puml



System_Boundary(AB7gRm4G0FDSwC6Ax9Br, "CH" ) {
    ' CLASSES =======
    ContainerDb(lzbazUSB1JSCrGUmiIvS, "XML Bank Movemnts", "", "")
    ContainerDb(sdXhz2x5m12JfZI7CPqK, "XML Payment Requests File", "", "")
    ContainerDb(09BlbXVqavc3SISvhm3x, "XLS Bank Executed Payments File", "", "")
    Component(TC84Zedf7r0MPG7SEkx2, "TC84Zedf7r0MPG7SEkx2", "")
    ContainerDb(6zrbWT3rue9s7yTmq2vt, "Basico Executed Payments File", "", "")
}


' NEIGHBOR CLASSES =======
Person(dJ9mBEcPcpgDp4FzPGBJ, "Bank", "")
System(AdhsdndKmvhsBWvLfJTK, "Member Service System", "")
System(7yUxSWwQWb7vyfM17Jbo, "Basico Bots", "")
System(soKzn6Drl9ZnctLZPvDw, "Finance System", "")


' SUB DIAGRAM CONNECTIONS ======= Base : [AB7gRm4G0FDSwC6Ax9Br]
' CONNECTION : [Export Payments] [dJ9mBEcPcpgDp4FzPGBJ] [09BlbXVqavc3SISvhm3x] [outgoing]
Rel(dJ9mBEcPcpgDp4FzPGBJ, 09BlbXVqavc3SISvhm3x, "Export Payments" )
' CONNECTION : [Uploading payments file] [sdXhz2x5m12JfZI7CPqK] [dJ9mBEcPcpgDp4FzPGBJ] [outgoing]
Rel(sdXhz2x5m12JfZI7CPqK, dJ9mBEcPcpgDp4FzPGBJ, "Uploading payments file" )
' CONNECTION : [Export movements] [dJ9mBEcPcpgDp4FzPGBJ] [lzbazUSB1JSCrGUmiIvS] [outgoing]
Rel(dJ9mBEcPcpgDp4FzPGBJ, lzbazUSB1JSCrGUmiIvS, "Export movements" )
' CONNECTION : [Manual Import] [6zrbWT3rue9s7yTmq2vt] [soKzn6Drl9ZnctLZPvDw] [outgoing]
Rel(6zrbWT3rue9s7yTmq2vt, soKzn6Drl9ZnctLZPvDw, "Manual Import" )
' CONNECTION : [Process incoming payment] [09BlbXVqavc3SISvhm3x] [7yUxSWwQWb7vyfM17Jbo] [outgoing]
Rel(09BlbXVqavc3SISvhm3x, 7yUxSWwQWb7vyfM17Jbo, "Process incoming payment" )
' CONNECTION : [Write movements] [lzbazUSB1JSCrGUmiIvS] [AdhsdndKmvhsBWvLfJTK] [outgoing]
Rel(lzbazUSB1JSCrGUmiIvS, AdhsdndKmvhsBWvLfJTK, "Write movements" )
' CONNECTION : [Generate XML with Payments] [soKzn6Drl9ZnctLZPvDw] [sdXhz2x5m12JfZI7CPqK] [outgoing]
Rel(soKzn6Drl9ZnctLZPvDw, sdXhz2x5m12JfZI7CPqK, "Generate XML with Payments" )


@enduml
