@startuml
'https://plantuml.com/class-diagram
' CONVERT ICEPANEL DIAGRAM ===========
' Converter          : it.brunasti.icepanel.tools.IcePanelToPlantUmlConverter
' IcePanel JSON File : [./examples/pg/pg-001.json]
' Configuration      : [./examples/pg/config.json]
' Generated at       : Wed Apr 17 11:06:08 CEST 2024

!include https://raw.githubusercontent.com/plantuml-stdlib/C4-PlantUML/master/C4_Context.puml
!include https://raw.githubusercontent.com/plantuml-stdlib/C4-PlantUML/master/C4_Component.puml



System_Boundary(hPa1gkYEDR8ckn11BmCT, "Reporting" ) {
    ' CLASSES =======
    Component(830mvzOBd9mjs0ueDxHQ, "830mvzOBd9mjs0ueDxHQ", "" )
    Component(dEiIJVGFUes52kwYOBfJ, "Apollo Reporting Tool", "" )
    ContainerDb(oVGxmBWAZwzORBGnm63k, "Apollo Datalake", "", "" )
}


' NEIGHBOR CLASSES =======


' CONNECTIONS =======


@enduml
