@startuml
' CONVERT ICEPANEL FLOW DIAGRAM ===========
' Converter          : it.brunasti.icepanel.tools.IcePanelToPlantUmlConverter
' IcePanel JSON File : [./examples/pg/pg-001.json]
' Configuration      : [./examples/pg/config.json]
' Generated at       : Wed Apr 10 09:16:05 CEST 2024

!include https://raw.githubusercontent.com/plantuml-stdlib/C4-PlantUML/master/C4_Context.puml
!include https://raw.githubusercontent.com/plantuml-stdlib/C4-PlantUML/master/C4_Component.puml

title Enrollment


' Elements =======
' Steps =======
participant "Prospect" as tWBMOSLhpcqKS34CzvM1 
participant "POS" as Dh7TjqtXo9JVsCCn3bol 
participant "Member" as Df8PP21Dc8ejtFQtIHmV 
participant "Member" as Df8PP21Dc8ejtFQtIHmV 
participant "Access Control" as vgrxHGsMNRMr3oRKap7i 
participant "Gym Machine" as 1nzUjBx1BzsmaX25lJHI 
participant "Access Control" as vgrxHGsMNRMr3oRKap7i 

tWBMOSLhpcqKS34CzvM1 -> Dh7TjqtXo9JVsCCn3bol : 1 Pays
tWBMOSLhpcqKS34CzvM1 -> Df8PP21Dc8ejtFQtIHmV : 2 
Df8PP21Dc8ejtFQtIHmV -> vgrxHGsMNRMr3oRKap7i : 4 Access Gym Club
Df8PP21Dc8ejtFQtIHmV -> 1nzUjBx1BzsmaX25lJHI : 5 Uses
Df8PP21Dc8ejtFQtIHmV -> vgrxHGsMNRMr3oRKap7i : 6 Exits


@enduml
