@startuml
'https://plantuml.com/class-diagram
' CONVERT ICEPANEL DIAGRAM ===========
' Converter          : it.brunasti.icepanel.tools.IcePanelToPlantUmlConverter
' IcePanel JSON File : [./examples/pg/pg-001.json]
' Configuration      : [./examples/pg/config.json]
' Generated at       : Wed Apr 10 17:38:19 CEST 2024

!include https://raw.githubusercontent.com/plantuml-stdlib/C4-PlantUML/master/C4_Context.puml
!include https://raw.githubusercontent.com/plantuml-stdlib/C4-PlantUML/master/C4_Component.puml



' CLASSES =======
System(8sWku9QFGqcPeNQStcsD, "Swiss Salary", "null" )
System(lGcP2Z0tsaJ5X8sJbiqe, "Robotics Relate IT", "null" )
ContainerDb(lzbazUSB1JSCrGUmiIvS, "XML Bank Movemnts", "null", "" )
Component(Bt0upOQ7ISx0R8IRiY7Y, "Static WebSite", "null" )
Person(FBBbTGT0oOXfeMyhwVyC, "Sompop Khamchoo", "null" )
System(2p8Khp4ecjAr7jWOw1rF, "Modellia - (survey)", "null" )
Component(IBWaUUzUjXn4rwTwok5k, "Concardis", "null" )
Container(5WKulSoGilOyWkIT57li, "ServiceNow WebSite", "null", "" )
Person(KpYA4jfUm7DneGIwDLve, "Jake Rostron", "null" )
Person(QZlQ9DNfCiQS6jQoJxej, "Jodie Whitter", "null" )
System(nStILm5s1k5PjSKTtx6M, "WebSite DK", "null" )
System(UpEFJxsN4ZWEpN0e8RgJ, "Boditrax", "null" )
Component(ccjXxgy74gi9Z75BYdQl, "Agilea (CRM)", "null" )
ContainerDb(2edKKQBcy2AdyQ3RAVWk, "Agilea DB", "null", "" )
Component(sYLxW4jvnSXS0361wc3B, "TBC User Profile", "null" )
Component(zZAdJ3R6x990ODKCL5ex, "TBC Payment API", "null" )
System(AdhsdndKmvhsBWvLfJTK, "Member Service System", "null" )
Person(8jNpTltrLLDgEn6uCl8w, "Frederik Rasch Madsen", "null" )
Component(XWiacBLGn7k983RqmMWv, "MyFit App (membership app)", "null" )
Person(I9HRSQxIrrm3rr7LJ5jb, "Aleksandra Wyrwich ", "null" )
ContainerDb(NnTsKEkdWpfDh4c5RyvC, "Local DB", "null", "" )
Component(uPJOg6NqkRPVL5Day3b4, "Excel PowerQuery", "null" )
Person(A94K4k099KgmlXGfjn2k, "Finance", "null" )
ContainerDb(sdXhz2x5m12JfZI7CPqK, "XML Payment Requests File", "null", "" )
Person(Df8PP21Dc8ejtFQtIHmV, "Member", "null" )
System(fqghK38cmYiB9byRf22W, "Integration DK", "null" )
Component(AInfIdvnaXbaFmyIidHG, "Dynamic WebSite", "null" )
System(gdPnpYi2Xih4P6wLQX6x, "TBC WebShop", "null" )
Person(68ZBmGQQBqfkawQxvDDk, "Member Service Operator", "null" )
System(1nzUjBx1BzsmaX25lJHI, "Gym Machine", "null" )
Component(KZVaNoTMJp3IWrLzKwgE, "Agilea BackEnd", "null" )
Person(nCNagrErDOB3JMDOzS6m, "Daryl Watts", "null" )
System(l7kJveASOMuUr1n5XbYu, "Apps DK", "null" )
System(Dh7TjqtXo9JVsCCn3bol, "POS", "null" )
ContainerDb(09BlbXVqavc3SISvhm3x, "XLS Bank Executed Payments File", "null", "" )
Person(4YBP6BlFzBp8pOuJwQQE, "Lakshmana Davisetti", "null" )
Component(830mvzOBd9mjs0ueDxHQ, "830mvzOBd9mjs0ueDxHQ", "null" )
System(SLmOFIXEutPoocdCdOE1, "Agilea (CRM)", "null" )
Person(LV2WD5SPjO4cbOAOnQ3R, "Jordan Woodley", "null" )
Component(S9hMClYptC27gpcb8h11, "Standard reports", "null" )
Person(NaJIADIPPqioEnMsZKFv, "Paolo", "null" )
System(ecklUQ6EmAaBAnOEPoBj, "CMA: Talentsoft to Zenergy", "null" )
Component(aE7OfZew41kPVk1SABBx, "TBC WebShop", "null" )
System(XyelrH1G0uxlThooT8jX, "Web Site", "null" )
System(H2t4baiWQlMGdfJBllnY, "Google Tag Manager", "null" )
Person(tqwJyVeVwbC3aj0tpKJH, "James Keiller", "null" )
Person(ocSPSt7sJwv7vL7dW0Wu, "Tom Bitter ", "null" )
Person(1wd6WWhc36tXZPDMAHGd, "Jacob Schaltz", "null" )
Component(NnSOwS6ppZmyWP4ygDuc, "Predefined Agilea Report", "null" )
Person(FsyGpvOu3nIbx1y3FFwf, "Dan Jones", "null" )
System(SLMBPAA5stAJyw9w6YTR, "TBC Member Service", "null" )
System(hPa1gkYEDR8ckn11BmCT, "Reporting", "null" )
Component(OaNn8XJbXv09gCQRz3AR, "Fixed Assets BC Module ", "null" )
ContainerDb(wOR937sPvgoWsOOpbtjl, "Email Address Zip File", "null", "" )
Component(BDy6EhnLdszv0o1UYCZp, "Homepage  - TBC Plugins", "null" )
System(zHL1ZXA9aErWQOFhD4qW, "Infrastructure - DK", "null" )
Container(L5SXGD6iXvA78tETTY6B, "ServiceNow  - Standard reports", "null", "" )
System(7yUxSWwQWb7vyfM17Jbo, "Basico Bots", "null" )
Component(dEiIJVGFUes52kwYOBfJ, "Apollo Reporting Tool", "null" )
System(WPA6hhdMorMwznakpPox, "CMA: Talentsoft to Planday", "null" )
Component(w8uGBpoOuSbjImUW8RfU, "ServiceNow", "null" )
Person(nsHGSpPSB65xQVEo95eL, "Andy Caddy", "null" )
Component(ZEp4TXWq29d0jSeELGSI, "Finance BC Module", "null" )
System(AB7gRm4G0FDSwC6Ax9Br, "CH", "null" )
System(vgrxHGsMNRMr3oRKap7i, "Access Control", "null" )
System(CwYK3KziEmXqFacwvvOw, "Payment IQ (Bambora)", "null" )
Person(PQmlX7q91Kh3Yf0F3HKA, "Martin Neble Green", "null" )
Component(TC84Zedf7r0MPG7SEkx2, "TC84Zedf7r0MPG7SEkx2", "null" )
Component(q8mphiB74ORpViZtWerc, "Card Reader", "null" )
System(aMYszCJvHb6cP7hiHw7f, "Nayax Vending Machine", "null" )
Person(30kdN3ZfUiaC147oEUgD, "Jack", "null" )
Person(xvtSOwqgkJuiS1AUfHtq, "Stefanie Fässler", "null" )
System(hcEeueNwY7CA019xqvl1, "B2B DK", "null" )
Component(3gBTkmv6ewqmKpnbn5XC, "PowerBI ", "null" )
Person(gyFaqXTUHNWi35U8x75B, "Ellen Robinson ", "null" )
Person(lzhQlWw0cvbzHdfNSybV, "Torben Torndahl Madsen ", "null" )
Component(HkTFrWwxNCqnhXTIXGtP, "LGF Booking (classes)", "null" )
System(YHg6gKwLEO5UAl3lfBtq, "Medallia (survey)", "null" )
Person(xG1SdOSA0DNgOQpu3sQf, "ex Fabian Eberle", "null" )
System(rpY5DxBdu7IEJKXe5Emh, "Swiss Salary BC Module", "null" )
System(GBRK2jW2bebbc8fWudh4, "Business and BackEnd - DK", "null" )
Component(EIJpNn9u7hgumXpmrcKx, "Access Control Hardware", "null" )
System(77z3GNYECULedfVTLceW, "Planday to Workplace", "null" )
System(Rprhv7hrshfmdvxFZcy7, "Agilea  - GAT Direct - Connect", "null" )
Person(hfRuKq27a6ZoZFlPtCWV, "Guest", "null" )
Person(xAUvR8Pfbnu2Rdl1PxL0, "Anders", "null" )
Person(ujSNtdaG7eKXiAqnQU6E, "CRM Account Receivable", "null" )
Component(3AscZ6uydpMZWsDirR10, "TBC Member Service", "null" )
Person(Z4bU5pNQCdeeNEnA1ez2, "Flemming", "null" )
System(0utkblCrFlZ98WxgoV4r, "Planday to LearningBank", "null" )
Person(bXWevRXRAy4B5zBAHrcI, "Graham Sundman", "null" )
Person(yxSolsmKtSMWI2da2IaD, "John Thixton", "null" )
Container(89UjCMyoDzRPm09TGMCZ, "ServiceNow - Core", "null", "" )
System(M4BOHpe8QgPpzQwaDVjm, "?? Unknown ??", "null" )
Person(VHvtx6bRzcO3NXYLpZD8, "Allan Alexander", "null" )
System(jSH31KrEZPWsgMgpk5Pl, "Mobile App", "null" )
Component(loR8IBnH8IvXoAVkXKxy, "Gantner Connector", "null" )
System(nGVRgXdObsLmDN7RmRCv, "Drink Machine", "null" )
System(hMTXPO2qds4ypEVlH0TC, "Mail Service", "null" )
System(dDrI9W8JoddtjUtcYM04, "UK/US/UAE", "null" )
Component(dB0dSFz9vWxK3sHTYoeN, "Ms Dynamics", "null" )
Component(s7euwZEIODsQskRUz8sq, "Document Capture BC Module", "null" )
Component(O6KajvAyVoBTw6HQArRz, "Wexer  - (virtual courses)", "null" )
Person(g1cGlwqdjoOmA7N5PpxG, "Florian Stern ", "null" )
Person(AMArsaUOgqE6KskBetpH, "Lee", "null" )
ContainerDb(oVGxmBWAZwzORBGnm63k, "Apollo Datalake", "null", "" )
Component(SIfTHbXR8kSApPyFqsd9, "PostFinance", "null" )
ContainerDb(6zrbWT3rue9s7yTmq2vt, "Basico Executed Payments File", "null", "" )
ContainerDb(HthjED489hlif2qbZPWs, "Agilea Export Database", "null", "" )
System(XgfAWPa7fIhJNEKkBsFu, "CMA: Talentsoft to Azure AD", "null" )
Component(Pe8ulmlmKE14nN8zxVKI, "Access Control Software System", "null" )
System(soKzn6Drl9ZnctLZPvDw, "Finance System", "null" )
System(J97hhgZT0oQY9pxrefax, "FW API", "null" )
Component(Lmcmoump6qMx52ccGHD9, "TBC myPureGym", "null" )
Container(NVzttd0H1pzo67Z0guTw, "ServiceNow API", "null", "" )
Person(dJ9mBEcPcpgDp4FzPGBJ, "Bank", "null" )
System(nWx1zIRMw0TdhvWCNIQ0, "Payment Provider", "null" )
Component(GuE8eWaHXObRqHjbEd48, "Agilea WebSite", "null" )
Person(oRWUt1MEkGzsjxGUyu1m, "Club Clerk", "null" )
Person(tWBMOSLhpcqKS34CzvM1, "Prospect", "null" )
Component(symQsnQ4xP2tak7w7OaM, "POS (ILS Retail)  BC Module", "null" )
Component(tUwesLk4JNiuUO6JJFiZ, "Classes booking", "null" )
Component(aqahI4H2TS1bek5eriv4, "Clerk Console", "null" )
System(fhpop0p1F3Q5SH6sW7Ie, "Exterrnal Equipment Maintenance", "null" )
Person(Gl98BoHAVzjhoEfzW22z, "Luca Kyburz", "null" )
System(byZhd62KzpD3gyQiquJP, "Agilic", "null" )
Person(pQdt7xK7tyooOlXDp01L, "Carl Stokes", "null" )
Person(5gELAvR5vUNER5UJDdEo, "Laura Cross", "null" )
ContainerDb(XTWjqMq5ZdJ9UR1KxPex, "Excel Files", "null", "" )
System(m9tnz7nlm8NuRuYhvv9o, "DK", "null" )
Component(iEGXnGRxKkVdQr2sWdDX, "Lanista  - (training planning)", "null" )


' CONNECTIONS =======
Rel(tWBMOSLhpcqKS34CzvM1, Dh7TjqtXo9JVsCCn3bol, "Payment" )
Rel(UpEFJxsN4ZWEpN0e8RgJ, AdhsdndKmvhsBWvLfJTK, "API" )
Rel(AdhsdndKmvhsBWvLfJTK, UpEFJxsN4ZWEpN0e8RgJ, "Return of API" )
Rel(soKzn6Drl9ZnctLZPvDw, lGcP2Z0tsaJ5X8sJbiqe, "Data on Payments" )
Rel(SLMBPAA5stAJyw9w6YTR, aE7OfZew41kPVk1SABBx, "Club information - Contract information - Coupon information - FAQ" )
Rel(aqahI4H2TS1bek5eriv4, q8mphiB74ORpViZtWerc, "Start Payment" )
Rel(q8mphiB74ORpViZtWerc, aqahI4H2TS1bek5eriv4, "Return of Start Payment" )
Rel(ccjXxgy74gi9Z75BYdQl, hPa1gkYEDR8ckn11BmCT, "Export Database" )
Rel(UpEFJxsN4ZWEpN0e8RgJ, KZVaNoTMJp3IWrLzKwgE, "API" )
Rel(Df8PP21Dc8ejtFQtIHmV, vgrxHGsMNRMr3oRKap7i, "Get authorisation to enter" )
Rel(dJ9mBEcPcpgDp4FzPGBJ, 09BlbXVqavc3SISvhm3x, "Export Payments" )
Rel(Df8PP21Dc8ejtFQtIHmV, Dh7TjqtXo9JVsCCn3bol, "CreditCard / DebitCard" )
Rel(Df8PP21Dc8ejtFQtIHmV, 1nzUjBx1BzsmaX25lJHI, "Exercises" )
Rel(hfRuKq27a6ZoZFlPtCWV, Df8PP21Dc8ejtFQtIHmV, "Becomes" )
Rel(SLMBPAA5stAJyw9w6YTR, BDy6EhnLdszv0o1UYCZp, "Unnamed connection" )
Rel(XyelrH1G0uxlThooT8jX, SLmOFIXEutPoocdCdOE1, "Access Member Data" )
Rel(SLmOFIXEutPoocdCdOE1, XyelrH1G0uxlThooT8jX, "Return of Access Member Data" )
Rel(Df8PP21Dc8ejtFQtIHmV, AInfIdvnaXbaFmyIidHG, "Dynamic activities" )
Rel(AInfIdvnaXbaFmyIidHG, Df8PP21Dc8ejtFQtIHmV, "Return of Dynamic activities" )
Rel(Rprhv7hrshfmdvxFZcy7, AdhsdndKmvhsBWvLfJTK, "API" )
Rel(AdhsdndKmvhsBWvLfJTK, Rprhv7hrshfmdvxFZcy7, "Return of API" )
Rel(BDy6EhnLdszv0o1UYCZp, NVzttd0H1pzo67Z0guTw, "Create Case" )
Rel(soKzn6Drl9ZnctLZPvDw, M4BOHpe8QgPpzQwaDVjm, "Unknown connections" )
Rel(M4BOHpe8QgPpzQwaDVjm, soKzn6Drl9ZnctLZPvDw, "Return of Unknown connections" )
Rel(ccjXxgy74gi9Z75BYdQl, wOR937sPvgoWsOOpbtjl, "Members Email Address" )
Rel(w8uGBpoOuSbjImUW8RfU, hMTXPO2qds4ypEVlH0TC, "emails" )
Rel(hMTXPO2qds4ypEVlH0TC, w8uGBpoOuSbjImUW8RfU, "Return of emails" )
Rel(hfRuKq27a6ZoZFlPtCWV, Df8PP21Dc8ejtFQtIHmV, "Becomes" )
Rel(dB0dSFz9vWxK3sHTYoeN, soKzn6Drl9ZnctLZPvDw, "Transmission every 30 minutes" )
Rel(sdXhz2x5m12JfZI7CPqK, dJ9mBEcPcpgDp4FzPGBJ, "Uploading payments file" )
Rel(Df8PP21Dc8ejtFQtIHmV, aMYszCJvHb6cP7hiHw7f, "Eat" )
Rel(gdPnpYi2Xih4P6wLQX6x, byZhd62KzpD3gyQiquJP, "Lead Information" )
Rel(w8uGBpoOuSbjImUW8RfU, fhpop0p1F3Q5SH6sW7Ie, "Maintenance Ticket" )
Rel(Dh7TjqtXo9JVsCCn3bol, symQsnQ4xP2tak7w7OaM, "Every 30'" )
Rel(aE7OfZew41kPVk1SABBx, SLMBPAA5stAJyw9w6YTR, "Staff Provision" )
Rel(tWBMOSLhpcqKS34CzvM1, Df8PP21Dc8ejtFQtIHmV, "Becomes" )
Rel(XWiacBLGn7k983RqmMWv, Lmcmoump6qMx52ccGHD9, "SSO" )
Rel(Lmcmoump6qMx52ccGHD9, SLmOFIXEutPoocdCdOE1, "Login - Upgrade Flats - Upgrade Contract - Change Member Information - Cancellation - Break" )
Rel(oRWUt1MEkGzsjxGUyu1m, 3AscZ6uydpMZWsDirR10, "Filling the Guests book" )
Rel(nGVRgXdObsLmDN7RmRCv, AdhsdndKmvhsBWvLfJTK, "API" )
Rel(AdhsdndKmvhsBWvLfJTK, nGVRgXdObsLmDN7RmRCv, "Return of API" )
Rel(dJ9mBEcPcpgDp4FzPGBJ, lzbazUSB1JSCrGUmiIvS, "Export movements" )
Rel(soKzn6Drl9ZnctLZPvDw, AdhsdndKmvhsBWvLfJTK, "David's" )
Rel(ccjXxgy74gi9Z75BYdQl, gdPnpYi2Xih4P6wLQX6x, "Changed prices, contract templates and member informations" )
Rel(hfRuKq27a6ZoZFlPtCWV, oRWUt1MEkGzsjxGUyu1m, "Asks for trial access" )
Rel(KZVaNoTMJp3IWrLzKwgE, 2p8Khp4ecjAr7jWOw1rF, "WebHook" )
Rel(ccjXxgy74gi9Z75BYdQl, w8uGBpoOuSbjImUW8RfU, "Tickets" )
Rel(Rprhv7hrshfmdvxFZcy7, KZVaNoTMJp3IWrLzKwgE, "API" )
Rel(BDy6EhnLdszv0o1UYCZp, aE7OfZew41kPVk1SABBx, "Price information" )
Rel(BDy6EhnLdszv0o1UYCZp, SLMBPAA5stAJyw9w6YTR, "Book trial training" )
Rel(6zrbWT3rue9s7yTmq2vt, soKzn6Drl9ZnctLZPvDw, "Manual Import" )
Rel(Df8PP21Dc8ejtFQtIHmV, gdPnpYi2Xih4P6wLQX6x, "Subscribe" )
Rel(aMYszCJvHb6cP7hiHw7f, KZVaNoTMJp3IWrLzKwgE, "REST API" )
Rel(Dh7TjqtXo9JVsCCn3bol, dJ9mBEcPcpgDp4FzPGBJ, "Check, Authorise, Transact" )
Rel(aMYszCJvHb6cP7hiHw7f, AdhsdndKmvhsBWvLfJTK, "API" )
Rel(AdhsdndKmvhsBWvLfJTK, aMYszCJvHb6cP7hiHw7f, "Return of API" )
Rel(09BlbXVqavc3SISvhm3x, 7yUxSWwQWb7vyfM17Jbo, "Process incoming payment" )
Rel(tWBMOSLhpcqKS34CzvM1, AInfIdvnaXbaFmyIidHG, "Subscribe new Membership" )
Rel(AInfIdvnaXbaFmyIidHG, tWBMOSLhpcqKS34CzvM1, "Return of Subscribe new Membership" )
Rel(hfRuKq27a6ZoZFlPtCWV, tWBMOSLhpcqKS34CzvM1, "Unnamed connection" )
Rel(aE7OfZew41kPVk1SABBx, SLMBPAA5stAJyw9w6YTR, "New Members" )
Rel(Rprhv7hrshfmdvxFZcy7, 1nzUjBx1BzsmaX25lJHI, "API" )
Rel(1nzUjBx1BzsmaX25lJHI, Rprhv7hrshfmdvxFZcy7, "Return of API" )
Rel(KZVaNoTMJp3IWrLzKwgE, w8uGBpoOuSbjImUW8RfU, "Flat File" )
Rel(Df8PP21Dc8ejtFQtIHmV, Dh7TjqtXo9JVsCCn3bol, "Payment" )
Rel(symQsnQ4xP2tak7w7OaM, ZEp4TXWq29d0jSeELGSI, "EoD Syncronization" )
Rel(lzbazUSB1JSCrGUmiIvS, AdhsdndKmvhsBWvLfJTK, "Write movements" )
Rel(Df8PP21Dc8ejtFQtIHmV, nGVRgXdObsLmDN7RmRCv, "Drinks" )
Rel(oRWUt1MEkGzsjxGUyu1m, AdhsdndKmvhsBWvLfJTK, "See Budget and Performances" )
Rel(BDy6EhnLdszv0o1UYCZp, SLMBPAA5stAJyw9w6YTR, "Club informations, content and picture" )
Rel(soKzn6Drl9ZnctLZPvDw, sdXhz2x5m12JfZI7CPqK, "Generate XML with Payments" )
Rel(vgrxHGsMNRMr3oRKap7i, Rprhv7hrshfmdvxFZcy7, "API" )
Rel(Rprhv7hrshfmdvxFZcy7, vgrxHGsMNRMr3oRKap7i, "Return of API" )
Rel(Dh7TjqtXo9JVsCCn3bol, soKzn6Drl9ZnctLZPvDw, "Data on Payments" )
Rel(3AscZ6uydpMZWsDirR10, ccjXxgy74gi9Z75BYdQl, "New Member" )
Rel(Df8PP21Dc8ejtFQtIHmV, Bt0upOQ7ISx0R8IRiY7Y, "Access www" )
Rel(Bt0upOQ7ISx0R8IRiY7Y, Df8PP21Dc8ejtFQtIHmV, "Return of Access www" )
Rel(sYLxW4jvnSXS0361wc3B, SLmOFIXEutPoocdCdOE1, "User Data" )
Rel(SLmOFIXEutPoocdCdOE1, sYLxW4jvnSXS0361wc3B, "Return of User Data" )
Rel(hMTXPO2qds4ypEVlH0TC, Df8PP21Dc8ejtFQtIHmV, "emails" )
Rel(Df8PP21Dc8ejtFQtIHmV, hMTXPO2qds4ypEVlH0TC, "Return of emails" )
Rel(gdPnpYi2Xih4P6wLQX6x, 3AscZ6uydpMZWsDirR10, "New - Subscription" )


' PARENT CONNECTIONS =======


@enduml
