@startuml
' CONVERT ICEPANEL FLOW DIAGRAM ===========
' Converter          : it.brunasti.icepanel.tools.IcePanelToPlantUmlConverter
' IcePanel JSON File : [./examples/ml/ml-001.json]
' Configuration      : [./examples/ml/config.json]
' Generated at       : Wed Apr 17 16:27:46 CEST 2024

!include https://raw.githubusercontent.com/plantuml-stdlib/C4-PlantUML/master/C4_Context.puml
!include https://raw.githubusercontent.com/plantuml-stdlib/C4-PlantUML/master/C4_Component.puml

title Interaction_flow


' Elements =======
' Steps =======
participant "CommerceTools System" as iihE1V4k7JDKwrS5GunC 
participant "Mollie  - API Extension - Julian" as 03XCn8Gai9J6GFDmJFfJ 
participant "Mollie  - API Extension - Julian" as 03XCn8Gai9J6GFDmJFfJ 
participant "Mollie System" as XPRwthglnMC6q9afCTyJ 
participant "Mollie System" as XPRwthglnMC6q9afCTyJ 
participant "Mollie - Notification Module - Mourice" as MRgvJ9ygR2wFH6SewIIW 
participant "Mollie - Notification Module - Mourice" as MRgvJ9ygR2wFH6SewIIW 

iihE1V4k7JDKwrS5GunC -> 03XCn8Gai9J6GFDmJFfJ : 1 Creates Order
03XCn8Gai9J6GFDmJFfJ -> XPRwthglnMC6q9afCTyJ : 2 Creates Order
XPRwthglnMC6q9afCTyJ -> MRgvJ9ygR2wFH6SewIIW : 3 Asynch - Creates Notification Order created
MRgvJ9ygR2wFH6SewIIW -> iihE1V4k7JDKwrS5GunC : 4 Processes Notification


@enduml
