@startuml
' CONVERT ICEPANEL FLOW DIAGRAM ===========
' Converter          : it.brunasti.icepanel.tools.IcePanelToPlantUmlConverter
' IcePanel JSON File : [./examples/ml/ml-001.json]
' Configuration      : [./examples/ml/config.json]
' Generated at       : Wed Apr 10 14:41:58 CEST 2024

!include https://raw.githubusercontent.com/plantuml-stdlib/C4-PlantUML/master/C4_Context.puml
!include https://raw.githubusercontent.com/plantuml-stdlib/C4-PlantUML/master/C4_Component.puml

title Customer buys


' Elements =======
' Steps =======
participant "Customer" as 901quKQooOwHHO3mAvwr 
participant "Merchant Shop" as 9xUmKihwlYUmsasTGOsv 
participant "Merchant Shop" as 9xUmKihwlYUmsasTGOsv 
participant "Merchant Shop" as 9xUmKihwlYUmsasTGOsv 
participant "CommerceTools" as BoNLOPSR4qOFGuDfePUN 
participant "CommerceTools" as BoNLOPSR4qOFGuDfePUN 
participant "Mollie" as BUVyar8CF5L9QiBG1ctm 
participant "Mollie" as BUVyar8CF5L9QiBG1ctm 
participant "Mollie" as BUVyar8CF5L9QiBG1ctm 
participant "Mollie" as BUVyar8CF5L9QiBG1ctm 
participant "Seller" as zT1BIuiGKsOS5Iyzaz4n 
participant "Seller" as zT1BIuiGKsOS5Iyzaz4n 

901quKQooOwHHO3mAvwr -> 9xUmKihwlYUmsasTGOsv : 1 Chooses products
901quKQooOwHHO3mAvwr -> 9xUmKihwlYUmsasTGOsv : 2 Checks out order
9xUmKihwlYUmsasTGOsv -> BoNLOPSR4qOFGuDfePUN : 3 Check out
BoNLOPSR4qOFGuDfePUN -> BUVyar8CF5L9QiBG1ctm : 4 Places payment request
BoNLOPSR4qOFGuDfePUN -> 9xUmKihwlYUmsasTGOsv : 5 Confirm Payment Request
9xUmKihwlYUmsasTGOsv -> 901quKQooOwHHO3mAvwr : 6 Asks to pay
901quKQooOwHHO3mAvwr -> BUVyar8CF5L9QiBG1ctm : 7 Views payment request
901quKQooOwHHO3mAvwr -> BUVyar8CF5L9QiBG1ctm : 8 Authorises payment
BUVyar8CF5L9QiBG1ctm -> BoNLOPSR4qOFGuDfePUN : 9 Confirms payment accepted
BoNLOPSR4qOFGuDfePUN -> 9xUmKihwlYUmsasTGOsv : 10 Confirm payment accepted
9xUmKihwlYUmsasTGOsv -> 901quKQooOwHHO3mAvwr : 11 Confirms order placed
BoNLOPSR4qOFGuDfePUN -> zT1BIuiGKsOS5Iyzaz4n : 12 Transmits order
zT1BIuiGKsOS5Iyzaz4n -> 901quKQooOwHHO3mAvwr : 13 Sends products


@enduml
