@startuml
'https://plantuml.com/class-diagram
' CONVERT ICEPANEL DIAGRAM ===========
' Converter          : it.brunasti.icepanel.tools.IcePanelToPlantUmlConverter
' IcePanel JSON File : [./examples/ml/ml-001.json]
' Configuration      : [./examples/ml/config.json]
' Generated at       : Thu Jan 09 17:33:19 CET 2025

!include https://raw.githubusercontent.com/plantuml-stdlib/C4-PlantUML/master/C4_Context.puml
!include https://raw.githubusercontent.com/plantuml-stdlib/C4-PlantUML/master/C4_Component.puml



Component(MRgvJ9ygR2wFH6SewIIW, "Mollie - Notification Module - Mourice", "The Notification module is a publicly exposed service which receives asynchronous notifications\nsent by Mollie.\n\nThrough notifications, Mollie provides asynchronous payment status changes like\nauthorized, captured, or refunded.\n\nThe notification module will process the notification sent by Mollie and\nmatch the commercetools payment for this notification, and modify commercetools payment accordingly.") { 
    ' CLASSES =======
    Container(H0bjyiKM0oWqEi6zJSnu, "Notification Module", "", "")
    Container(GecJ5QlG47xgNEoHmv9V, "webhook", "", "")
}


' NEIGHBOR CLASSES =======
Component(XPRwthglnMC6q9afCTyJ, "Mollie System", "Effortless payments, seamless checkout, multiple payment methods, powerful integrations, fast and\nflexible financing, robust security, an advanced dashboard and app – and even more.")
Container(B2danvdNerKouHi6xarl, "CommerceTools Core", "", "")


' SUB DIAGRAM CONNECTIONS ======= Base : [MRgvJ9ygR2wFH6SewIIW]
' CONNECTION : [Updates] [H0bjyiKM0oWqEi6zJSnu] [B2danvdNerKouHi6xarl] [outgoing]
Rel(H0bjyiKM0oWqEi6zJSnu, B2danvdNerKouHi6xarl, "Updates" )
' CONNECTION : [Reads Payment] [H0bjyiKM0oWqEi6zJSnu] [XPRwthglnMC6q9afCTyJ] [outgoing]
Rel(H0bjyiKM0oWqEi6zJSnu, XPRwthglnMC6q9afCTyJ, "Reads Payment" )
' CONNECTION : [Notification] [XPRwthglnMC6q9afCTyJ] [GecJ5QlG47xgNEoHmv9V] [outgoing]
Rel(XPRwthglnMC6q9afCTyJ, GecJ5QlG47xgNEoHmv9V, "Notification" )


@enduml
