@startuml
'https://plantuml.com/class-diagram
' CONVERT ICEPANEL DIAGRAM ===========
' Converter          : it.brunasti.icepanel.tools.IcePanelToPlantUmlConverter
' IcePanel JSON File : [./examples/ml/ml-001.json]
' Configuration      : [./examples/ml/config.json]
' Generated at       : Wed Apr 10 09:16:05 CEST 2024

!include https://raw.githubusercontent.com/plantuml-stdlib/C4-PlantUML/master/C4_Context.puml
!include https://raw.githubusercontent.com/plantuml-stdlib/C4-PlantUML/master/C4_Component.puml



Component(MRgvJ9ygR2wFH6SewIIW, "Mollie - Notification Module - Mourice", "The Notification module is a publicly exposed service which receives asynchronous notifications sent by Mollie.  Through notifications, Mollie provides asynchronous payment status changes like authorized, captured, or refunded.  The notification module will process the notification sent by Mollie and match the commercetools payment for this notification, and modify commercetools payment accordingly." ) { 
    ' CLASSES =======
    Container(H0bjyiKM0oWqEi6zJSnu, "Notification Module", "", "" )
    Container(GecJ5QlG47xgNEoHmv9V, "webhook", "", "" )
}


' NEIGHBOR CLASSES =======
Component(XPRwthglnMC6q9afCTyJ, "Mollie System", "Effortless payments, seamless checkout, multiple payment methods, powerful integrations, fast and flexible financing, robust security, an advanced dashboard and app – and even more." )
Container(B2danvdNerKouHi6xarl, "CommerceTools Core", "", "" )


' CONNECTIONS =======
Rel(H0bjyiKM0oWqEi6zJSnu, B2danvdNerKouHi6xarl, "Updates" )
Rel(H0bjyiKM0oWqEi6zJSnu, XPRwthglnMC6q9afCTyJ, "Reads Payment" )
Rel(XPRwthglnMC6q9afCTyJ, GecJ5QlG47xgNEoHmv9V, "Notification" )


@enduml
