@startuml
'https://plantuml.com/class-diagram
' CONVERT ICEPANEL DIAGRAM ===========
' Converter          : it.brunasti.icepanel.tools.IcePanelToPlantUmlConverter
' IcePanel JSON File : [./src/test/resources/icepanel-plain.json]
' Configuration      : [./docs/config.json]
' Generated at       : Sun Dec 29 18:49:47 CET 2024

!include https://raw.githubusercontent.com/plantuml-stdlib/C4-PlantUML/master/C4_Context.puml
!include https://raw.githubusercontent.com/plantuml-stdlib/C4-PlantUML/master/C4_Component.puml


' Include         : [./docs/include.txt] ---------
hide empty members
' Include end     : --------------------------


Component(4teQrlbMUj5LLqxdVcPK, "BAHPCA API", "") { 
    ' CLASSES =======
    Container(DqaxYHtWGYqlWeYgZkyP, "Common Lib", "", "")
    Container(Nr2rq32hBezwoAGeNT2U, "BAHPCA API Code", "", "")
    Container(JOCj92Vc2CEAUN8hquBI, "Spring Framework", "", "")
}


' NEIGHBOR CLASSES =======
ContainerDb(MzZVLTUQ74KbySVwdHfZ, "OpenSearch", "", "")
Container(Vg8nvjzPDirSBRjT8K3Q, "Solr API Code", "", "")
Component(DzQ4VPgJYKxSkilz6snk, "BAHPCA_repo", "")
Component(6uyz5GXgHFSVjrwIwRKC, "Common_Repo", "")


' SUB DIAGRAM CONNECTIONS ======= Base : [4teQrlbMUj5LLqxdVcPK]
' CONNECTION : [Deployed as] [DzQ4VPgJYKxSkilz6snk] [Nr2rq32hBezwoAGeNT2U] [outgoing]
Rel(DzQ4VPgJYKxSkilz6snk, Nr2rq32hBezwoAGeNT2U, "Deployed as" )
' CONNECTION : [Uses] [Vg8nvjzPDirSBRjT8K3Q] [DqaxYHtWGYqlWeYgZkyP] [outgoing]
Rel(Vg8nvjzPDirSBRjT8K3Q, DqaxYHtWGYqlWeYgZkyP, "Uses" )
' CONNECTION : [reads data] [MzZVLTUQ74KbySVwdHfZ] [Nr2rq32hBezwoAGeNT2U] [outgoing]
Rel(MzZVLTUQ74KbySVwdHfZ, Nr2rq32hBezwoAGeNT2U, "reads data" )
' CONNECTION : [Based on] [Vg8nvjzPDirSBRjT8K3Q] [JOCj92Vc2CEAUN8hquBI] [outgoing]
Rel(Vg8nvjzPDirSBRjT8K3Q, JOCj92Vc2CEAUN8hquBI, "Based on" )
' CONNECTION : [Based on] [Nr2rq32hBezwoAGeNT2U] [JOCj92Vc2CEAUN8hquBI] [outgoing]
Rel(Nr2rq32hBezwoAGeNT2U, JOCj92Vc2CEAUN8hquBI, "Based on" )
' CONNECTION : [Deployed as] [6uyz5GXgHFSVjrwIwRKC] [DqaxYHtWGYqlWeYgZkyP] [outgoing]
Rel(6uyz5GXgHFSVjrwIwRKC, DqaxYHtWGYqlWeYgZkyP, "Deployed as" )


@enduml
