@startuml
'https://plantuml.com/class-diagram
' CONVERT ICEPANEL DIAGRAM ===========
' Converter          : it.brunasti.icepanel.tools.IcePanelToPlantUMLConverter
' IcePanel JSON File : [./src/test/resources/icepanel-plain-02.json]
' Configuration      : [./docs/config.json]
' Generated at       : Mon Apr 08 14:04:31 CEST 2024

!include https://raw.githubusercontent.com/plantuml-stdlib/C4-PlantUML/master/C4_Context.puml
!include https://raw.githubusercontent.com/plantuml-stdlib/C4-PlantUML/master/C4_Component.puml



Component(OmsC5XSTv64h2ua9yNDK, "Solr API", "" ) { 
    ' CLASSES =======
    Container(Vg8nvjzPDirSBRjT8K3Q, "Solr API Code", "", "" )
}


' NEIGHBOR CLASSES =======
Container(JOCj92Vc2CEAUN8hquBI, "Spring Framework", "", "" )
ContainerDb(MzZVLTUQ74KbySVwdHfZ, "OpenSearch", "", "" )
Component(heuHGHPQyPiOSCrreA29, "API Gateway", "" )
Container(DqaxYHtWGYqlWeYgZkyP, "Common Lib", "", "" )
Component(nd7uOWs4bfaeXm73vKFa, "Solr_Repo", "" )


' CONNECTIONS =======
Rel(MzZVLTUQ74KbySVwdHfZ, Vg8nvjzPDirSBRjT8K3Q, "reads data" )
Rel(Vg8nvjzPDirSBRjT8K3Q, DqaxYHtWGYqlWeYgZkyP, "Uses" )
Rel(nd7uOWs4bfaeXm73vKFa, Vg8nvjzPDirSBRjT8K3Q, "Deploy" )
Rel(Vg8nvjzPDirSBRjT8K3Q, JOCj92Vc2CEAUN8hquBI, "Based on" )
Rel(heuHGHPQyPiOSCrreA29, Vg8nvjzPDirSBRjT8K3Q, "Accesses API implementations" )


@enduml
