@startuml
' CONVERT ICEPANEL FLOW DIAGRAM ===========
' Converter          : it.brunasti.icepanel.tools.IcePanelToPlantUmlConverter
' IcePanel JSON File : [./src/test/resources/icepanel-plain.json]
' Configuration      : [./docs/config.json]
' Generated at       : Wed Apr 17 11:06:08 CEST 2024

!include https://raw.githubusercontent.com/plantuml-stdlib/C4-PlantUML/master/C4_Context.puml
!include https://raw.githubusercontent.com/plantuml-stdlib/C4-PlantUML/master/C4_Component.puml


' Include         : [./docs/include.txt] ---------
hide empty members
' Include end     : --------------------------
title Transfer data to OpenSearch by Control-M Batch Flow


' Elements =======
' Steps =======
participant "Cache Management Tool (CMT)" as ca13KkX3DwaOlAXtqCBu 
participant "CMT Oracle" as HhxISGaz4P94iRFwLQgB 
participant "Clock" as gjWRDpkTJ13KPRmh36F5 
participant "Control-M - Stored Procedure" as HRtqQ8npZIhFIJyE4fny 
participant "Control-M - Stored Procedure" as HRtqQ8npZIhFIJyE4fny 
participant "CMT Oracle" as HhxISGaz4P94iRFwLQgB 
participant "Control-M" as fw0FSosDQxrXPus6KZ6i 
participant "Control-M" as fw0FSosDQxrXPus6KZ6i 
participant "Burst Controller" as iCsNVDctelyaR2c4wnkh 
participant "Burst Controller" as iCsNVDctelyaR2c4wnkh 
participant "MQ Series" as P8FRwIacDu7PGvfS8xYm 
participant "MQ Series" as P8FRwIacDu7PGvfS8xYm 
participant "Batch Controller" as FbHUk96QaZQVUumba63H 
participant "CMT Oracle" as HhxISGaz4P94iRFwLQgB 
participant "Batch Controller" as FbHUk96QaZQVUumba63H 
participant "CAPTWO" as JDgumJdxCj5dCURdCtKN 
participant "Batch Controller" as FbHUk96QaZQVUumba63H 
participant "Batch Controller" as FbHUk96QaZQVUumba63H 
participant "xDistributor" as CBSTDIDaQZluhMUnj5Mq 
participant "xDistributor" as CBSTDIDaQZluhMUnj5Mq 
participant "Config DB" as oTdOuXLuTyPzLeCjIYDx 
participant "Direct Connect" as p4yomm0RrOrYTNX8VvEg 

ca13KkX3DwaOlAXtqCBu -> HhxISGaz4P94iRFwLQgB : 1 Sets search criteria
gjWRDpkTJ13KPRmh36F5 -> HRtqQ8npZIhFIJyE4fny : 2 Activates the Control-M which execute the Stored Procedure on CMT DB to prepare the data to be exported
HRtqQ8npZIhFIJyE4fny -> HhxISGaz4P94iRFwLQgB : 3 Invokes Stored Procedure on Oracle DB
gjWRDpkTJ13KPRmh36F5 -> fw0FSosDQxrXPus6KZ6i : 4 Activates Control-M to trigger Bust Controller every minute
fw0FSosDQxrXPus6KZ6i -> iCsNVDctelyaR2c4wnkh : 5 Pings the Burst Controller every minute to make it load one more message into MQ Series with one more research
iCsNVDctelyaR2c4wnkh -> P8FRwIacDu7PGvfS8xYm : 6 Creates a message for the Batch Controller with the ids for a new request and post it into MQ Series
P8FRwIacDu7PGvfS8xYm -> FbHUk96QaZQVUumba63H : 7 Extracts next Message with Batch Instruction
HhxISGaz4P94iRFwLQgB -> FbHUk96QaZQVUumba63H : 8 Reads the query details form the CMT DB based on the ids in the MS Queries message
JDgumJdxCj5dCURdCtKN -> FbHUk96QaZQVUumba63H : 9 Enriches query details with info from CAPTWO
FbHUk96QaZQVUumba63H -> CBSTDIDaQZluhMUnj5Mq : 10 Submits to xDistributor a request for additional details for the query
CBSTDIDaQZluhMUnj5Mq -> oTdOuXLuTyPzLeCjIYDx : 11 Extracts the request details
CBSTDIDaQZluhMUnj5Mq -> FbHUk96QaZQVUumba63H : 12 Returns the enriched details
FbHUk96QaZQVUumba63H -> p4yomm0RrOrYTNX8VvEg : 13 Sends offer data to OpenSearch via AWS infra


@enduml
