@startuml
'https://plantuml.com/class-diagram
' CONVERT ICEPANEL DIAGRAM ===========
' Converter          : it.brunasti.icepanel.tools.IcePanelToPlantUMLConverter
' IcePanel JSON File : [./src/test/resources/icepanel-plain-02.json]
' Configuration      : [./docs/config.json]
' Generated at       : Fri Apr 05 14:47:32 CEST 2024

!include https://raw.githubusercontent.com/plantuml-stdlib/C4-PlantUML/master/C4_Context.puml
!include https://raw.githubusercontent.com/plantuml-stdlib/C4-PlantUML/master/C4_Component.puml



System_Boundary(9vmw8B9ZSNjTOfwkQyX1, "AWS" ) {
    ' CLASSES =======
}


' NEIGHBOR CLASSES =======


' CONNECTIONS =======


@enduml
