@startuml
'https://plantuml.com/class-diagram
' CONVERT ICEPANEL DIAGRAM ===========
' Converter          : it.brunasti.icepanel.tools.IcePanelToPlantUmlConverter
' IcePanel JSON File : [./src/test/resources/icepanel-plain.json]
' Configuration      : [./docs/config.json]
' Generated at       : Sun Dec 29 18:49:47 CET 2024

!include https://raw.githubusercontent.com/plantuml-stdlib/C4-PlantUML/master/C4_Context.puml
!include https://raw.githubusercontent.com/plantuml-stdlib/C4-PlantUML/master/C4_Component.puml


' Include         : [./docs/include.txt] ---------
hide empty members
' Include end     : --------------------------


Component(OmsC5XSTv64h2ua9yNDK, "Solr API", "") { 
    ' CLASSES =======
    Container(Vg8nvjzPDirSBRjT8K3Q, "Solr API Code", "", "")
}


' NEIGHBOR CLASSES =======
Container(JOCj92Vc2CEAUN8hquBI, "Spring Framework", "", "")
ContainerDb(MzZVLTUQ74KbySVwdHfZ, "OpenSearch", "", "")
Component(heuHGHPQyPiOSCrreA29, "API Gateway", "")
Container(DqaxYHtWGYqlWeYgZkyP, "Common Lib", "", "")
Component(nd7uOWs4bfaeXm73vKFa, "Solr_Repo", "")


' SUB DIAGRAM CONNECTIONS ======= Base : [OmsC5XSTv64h2ua9yNDK]
' CONNECTION : [reads data] [MzZVLTUQ74KbySVwdHfZ] [Vg8nvjzPDirSBRjT8K3Q] [outgoing]
Rel(MzZVLTUQ74KbySVwdHfZ, Vg8nvjzPDirSBRjT8K3Q, "reads data" )
' CONNECTION : [Uses] [Vg8nvjzPDirSBRjT8K3Q] [DqaxYHtWGYqlWeYgZkyP] [outgoing]
Rel(Vg8nvjzPDirSBRjT8K3Q, DqaxYHtWGYqlWeYgZkyP, "Uses" )
' CONNECTION : [Deployed as] [nd7uOWs4bfaeXm73vKFa] [Vg8nvjzPDirSBRjT8K3Q] [outgoing]
Rel(nd7uOWs4bfaeXm73vKFa, Vg8nvjzPDirSBRjT8K3Q, "Deployed as" )
' CONNECTION : [Based on] [Vg8nvjzPDirSBRjT8K3Q] [JOCj92Vc2CEAUN8hquBI] [outgoing]
Rel(Vg8nvjzPDirSBRjT8K3Q, JOCj92Vc2CEAUN8hquBI, "Based on" )
' CONNECTION : [Accesses API implementations] [heuHGHPQyPiOSCrreA29] [Vg8nvjzPDirSBRjT8K3Q] [outgoing]
Rel(heuHGHPQyPiOSCrreA29, Vg8nvjzPDirSBRjT8K3Q, "Accesses API implementations" )


@enduml
