@startuml
'https://plantuml.com/class-diagram
' CONVERT ICEPANEL DIAGRAM ===========
' Converter          : it.brunasti.icepanel.tools.IcePanelToPlantUmlConverter
' IcePanel JSON File : [./src/test/resources/icepanel-plain.json]
' Configuration      : [./docs/config.json]
' Generated at       : Thu Jan 09 17:33:19 CET 2025

!include https://raw.githubusercontent.com/plantuml-stdlib/C4-PlantUML/master/C4_Context.puml
!include https://raw.githubusercontent.com/plantuml-stdlib/C4-PlantUML/master/C4_Component.puml


' Include         : [./docs/include.txt] ---------
hide empty members
' Include end     : --------------------------


System_Boundary(axBWvtIPYmpByC3xkoHt, "GitHub" ) {
    ' CLASSES =======
    Component(DzQ4VPgJYKxSkilz6snk, "BAHPCA_repo", "")
    Component(6uyz5GXgHFSVjrwIwRKC, "Common_Repo", "")
    Component(nd7uOWs4bfaeXm73vKFa, "Solr_Repo", "")
    Component(aik6DuJQc2KhSf4c5QZV, "CA Exporter", "")
    Component(F2hUPV68esNdYOZlEDZp, "Git Pipeline", "")
    Component(sevE1WSEK6p75cxmStkb, "Git Actions", "")
}


' NEIGHBOR CLASSES =======
Component(OmsC5XSTv64h2ua9yNDK, "Solr API", "")
Container(Nr2rq32hBezwoAGeNT2U, "BAHPCA API Code", "", "")
Person(oTbmuU7ncIHqPnGupIDk, "Developer", "")
Container(Vg8nvjzPDirSBRjT8K3Q, "Solr API Code", "", "")
Component(4teQrlbMUj5LLqxdVcPK, "BAHPCA API", "")
Component(BxsQud7gKwTvBJQ0KNj2, "Commercial Analysis Export", "")
Container(DqaxYHtWGYqlWeYgZkyP, "Common Lib", "", "")


' SUB DIAGRAM CONNECTIONS ======= Base : [axBWvtIPYmpByC3xkoHt]
' CONNECTION : [Deployed as] [DzQ4VPgJYKxSkilz6snk] [Nr2rq32hBezwoAGeNT2U] [outgoing]
Rel(DzQ4VPgJYKxSkilz6snk, Nr2rq32hBezwoAGeNT2U, "Deployed as" )
' CONNECTION : [Develops] [oTbmuU7ncIHqPnGupIDk] [6uyz5GXgHFSVjrwIwRKC] [outgoing]
Rel(oTbmuU7ncIHqPnGupIDk, 6uyz5GXgHFSVjrwIwRKC, "Develops" )
' CONNECTION : [Deployed as] [nd7uOWs4bfaeXm73vKFa] [Vg8nvjzPDirSBRjT8K3Q] [outgoing]
Rel(nd7uOWs4bfaeXm73vKFa, Vg8nvjzPDirSBRjT8K3Q, "Deployed as" )
' CONNECTION : [Develops] [oTbmuU7ncIHqPnGupIDk] [DzQ4VPgJYKxSkilz6snk] [outgoing]
Rel(oTbmuU7ncIHqPnGupIDk, DzQ4VPgJYKxSkilz6snk, "Develops" )
' CONNECTION : [Deploy] [F2hUPV68esNdYOZlEDZp] [4teQrlbMUj5LLqxdVcPK] [outgoing]
Rel(F2hUPV68esNdYOZlEDZp, 4teQrlbMUj5LLqxdVcPK, "Deploy" )
' CONNECTION : [Develops] [oTbmuU7ncIHqPnGupIDk] [nd7uOWs4bfaeXm73vKFa] [outgoing]
Rel(oTbmuU7ncIHqPnGupIDk, nd7uOWs4bfaeXm73vKFa, "Develops" )
' CONNECTION : [Deployed via] [DzQ4VPgJYKxSkilz6snk] [F2hUPV68esNdYOZlEDZp] [outgoing]
Rel(DzQ4VPgJYKxSkilz6snk, F2hUPV68esNdYOZlEDZp, "Deployed via" )
' CONNECTION : [Deployed via] [nd7uOWs4bfaeXm73vKFa] [F2hUPV68esNdYOZlEDZp] [outgoing]
Rel(nd7uOWs4bfaeXm73vKFa, F2hUPV68esNdYOZlEDZp, "Deployed via" )
' CONNECTION : [Deployed via] [aik6DuJQc2KhSf4c5QZV] [F2hUPV68esNdYOZlEDZp] [outgoing]
Rel(aik6DuJQc2KhSf4c5QZV, F2hUPV68esNdYOZlEDZp, "Deployed via" )
' CONNECTION : [Deployed as] [6uyz5GXgHFSVjrwIwRKC] [DqaxYHtWGYqlWeYgZkyP] [outgoing]
Rel(6uyz5GXgHFSVjrwIwRKC, DqaxYHtWGYqlWeYgZkyP, "Deployed as" )
' CONNECTION : [Deploy] [F2hUPV68esNdYOZlEDZp] [OmsC5XSTv64h2ua9yNDK] [outgoing]
Rel(F2hUPV68esNdYOZlEDZp, OmsC5XSTv64h2ua9yNDK, "Deploy" )
' CONNECTION : [Develops] [oTbmuU7ncIHqPnGupIDk] [aik6DuJQc2KhSf4c5QZV] [outgoing]
Rel(oTbmuU7ncIHqPnGupIDk, aik6DuJQc2KhSf4c5QZV, "Develops" )
' CONNECTION : [Executes] [F2hUPV68esNdYOZlEDZp] [sevE1WSEK6p75cxmStkb] [outgoing]
Rel(F2hUPV68esNdYOZlEDZp, sevE1WSEK6p75cxmStkb, "Executes" )
' CONNECTION : [Deploy] [F2hUPV68esNdYOZlEDZp] [BxsQud7gKwTvBJQ0KNj2] [outgoing]
Rel(F2hUPV68esNdYOZlEDZp, BxsQud7gKwTvBJQ0KNj2, "Deploy" )


@enduml
