@startuml
'https://plantuml.com/class-diagram
' CONVERT ICEPANEL DIAGRAM ===========
' Converter          : it.brunasti.icepanel.tools.IcePanelToPlantUmlConverter
' IcePanel JSON File : [./src/test/resources/icepanel-plain.json]
' Configuration      : [./docs/config.json]
' Generated at       : Sun Dec 29 18:49:47 CET 2024

!include https://raw.githubusercontent.com/plantuml-stdlib/C4-PlantUML/master/C4_Context.puml
!include https://raw.githubusercontent.com/plantuml-stdlib/C4-PlantUML/master/C4_Component.puml


' Include         : [./docs/include.txt] ---------
hide empty members
' Include end     : --------------------------


System_Boundary(cpxxV9fxmR1pgCAxHFdB, "BAH CNG" ) {
    ' CLASSES =======
    Component(BxsQud7gKwTvBJQ0KNj2, "Commercial Analysis Export", "")
    Component(oLiyCOrWiJ4p4jQxIr1F, "OpenSearch Ingestion", "")
    Component(heuHGHPQyPiOSCrreA29, "API Gateway", "")
    Component(p4yomm0RrOrYTNX8VvEg, "Direct Connect", "")
    Component(hQNUt4ZkKRpf1tU4WmD7, "Cache Deletion System", "")
    Component(LOCysP2vMe5DXLAHEYdU, "OpenSearch Dashboard", "")
    Component(Xoxj4IX90NjN8wiNvxFB, "Network Load Balancer", "")
    Component(OmsC5XSTv64h2ua9yNDK, "Solr API", "")
    Component(MoA8eTudOD7sWkzZF9av, "Transit Gateway", "")
    Component(uFk6F6ZcKKvnkVRkCNgH, "FireWall", "")
    Component(4teQrlbMUj5LLqxdVcPK, "BAHPCA API", "")
    ContainerDb(N5ViUhQIiCffQr67385p, "BAH CA - SQL Server", "Steve Edgerton:\n\n- BAHSQL1.bah.ba.com\n- CNG , schema dbo.\n- 100.64.64.215\n- Account:\nbahsql-prd (147441800008)\n- TCP 1433\n\nLive and Test users\n\nSystem:\n\nWindows Server 2019 ,SQL Server\n2017, Domain BAH.ba.com", "")
    ContainerDb(MzZVLTUQ74KbySVwdHfZ, "OpenSearch", "", "")
}


' NEIGHBOR CLASSES =======
Person(wSyyLfkRhknshpX3pdWJ, "Internal Consumer", "")
Component(DzQ4VPgJYKxSkilz6snk, "BAHPCA_repo", "")
Component(6uyz5GXgHFSVjrwIwRKC, "Common_Repo", "")
System(LqXZYPgQ9UPjc7lqtp7S, "Akamai", "")
Component(nd7uOWs4bfaeXm73vKFa, "Solr_Repo", "")
Component(FbHUk96QaZQVUumba63H, "Batch Controller", "")
Component(F2hUPV68esNdYOZlEDZp, "Git Pipeline", "")
Person(mtyHirRmDImFDmca6URg, "Cache Admin", "")
Person(f1fiXJziytRGVe7hFuLo, "Commercial Analyst", "")


' SUB DIAGRAM CONNECTIONS ======= Base : [cpxxV9fxmR1pgCAxHFdB]
' CONNECTION : [reads data] [MzZVLTUQ74KbySVwdHfZ] [OmsC5XSTv64h2ua9yNDK] [outgoing]
Rel(MzZVLTUQ74KbySVwdHfZ, OmsC5XSTv64h2ua9yNDK, "reads data" )
' CONNECTION : [Accesses API implementations] [heuHGHPQyPiOSCrreA29] [4teQrlbMUj5LLqxdVcPK] [outgoing]
Rel(heuHGHPQyPiOSCrreA29, 4teQrlbMUj5LLqxdVcPK, "Accesses API implementations" )
' CONNECTION : [Deployed as] [DzQ4VPgJYKxSkilz6snk] [4teQrlbMUj5LLqxdVcPK] [outgoing]
Rel(DzQ4VPgJYKxSkilz6snk, 4teQrlbMUj5LLqxdVcPK, "Deployed as" )
' CONNECTION : [Access  secured systems] [LqXZYPgQ9UPjc7lqtp7S] [heuHGHPQyPiOSCrreA29] [outgoing]
Rel(LqXZYPgQ9UPjc7lqtp7S, heuHGHPQyPiOSCrreA29, "Access  secured systems" )
' CONNECTION : [Uses] [OmsC5XSTv64h2ua9yNDK] [4teQrlbMUj5LLqxdVcPK] [outgoing]
Rel(OmsC5XSTv64h2ua9yNDK, 4teQrlbMUj5LLqxdVcPK, "Uses" )
' CONNECTION : [reads data] [MzZVLTUQ74KbySVwdHfZ] [4teQrlbMUj5LLqxdVcPK] [outgoing]
Rel(MzZVLTUQ74KbySVwdHfZ, 4teQrlbMUj5LLqxdVcPK, "reads data" )
' CONNECTION : [Deployed as] [nd7uOWs4bfaeXm73vKFa] [OmsC5XSTv64h2ua9yNDK] [outgoing]
Rel(nd7uOWs4bfaeXm73vKFa, OmsC5XSTv64h2ua9yNDK, "Deployed as" )
' CONNECTION : [Retrieve Cache] [MzZVLTUQ74KbySVwdHfZ] [LOCysP2vMe5DXLAHEYdU] [outgoing]
Rel(MzZVLTUQ74KbySVwdHfZ, LOCysP2vMe5DXLAHEYdU, "Retrieve Cache" )
' CONNECTION : [Request Cache Data] [wSyyLfkRhknshpX3pdWJ] [Xoxj4IX90NjN8wiNvxFB] [outgoing]
Rel(wSyyLfkRhknshpX3pdWJ, Xoxj4IX90NjN8wiNvxFB, "Request Cache Data" )
' CONNECTION : [Deploy] [F2hUPV68esNdYOZlEDZp] [4teQrlbMUj5LLqxdVcPK] [outgoing]
Rel(F2hUPV68esNdYOZlEDZp, 4teQrlbMUj5LLqxdVcPK, "Deploy" )
' CONNECTION : [Based on] [OmsC5XSTv64h2ua9yNDK] [4teQrlbMUj5LLqxdVcPK] [outgoing]
Rel(OmsC5XSTv64h2ua9yNDK, 4teQrlbMUj5LLqxdVcPK, "Based on" )
' CONNECTION : [Flow] [p4yomm0RrOrYTNX8VvEg] [MoA8eTudOD7sWkzZF9av] [outgoing]
Rel(p4yomm0RrOrYTNX8VvEg, MoA8eTudOD7sWkzZF9av, "Flow" )
' CONNECTION : [OnPrem / AWS connectivity] [FbHUk96QaZQVUumba63H] [p4yomm0RrOrYTNX8VvEg] [outgoing]
Rel(FbHUk96QaZQVUumba63H, p4yomm0RrOrYTNX8VvEg, "OnPrem / AWS connectivity" )
' CONNECTION : [Access SQL Server] [uFk6F6ZcKKvnkVRkCNgH] [N5ViUhQIiCffQr67385p] [bidirectional]
Rel(uFk6F6ZcKKvnkVRkCNgH, N5ViUhQIiCffQr67385p, "Access SQL Server" )
Rel(N5ViUhQIiCffQr67385p, uFk6F6ZcKKvnkVRkCNgH, "Return of Access SQL Server" )
' CONNECTION : [Create Commercial Analysis Data] [BxsQud7gKwTvBJQ0KNj2] [uFk6F6ZcKKvnkVRkCNgH] [outgoing]
Rel(BxsQud7gKwTvBJQ0KNj2, uFk6F6ZcKKvnkVRkCNgH, "Create Commercial Analysis Data" )
' CONNECTION : [Store Offers] [oLiyCOrWiJ4p4jQxIr1F] [MzZVLTUQ74KbySVwdHfZ] [outgoing]
Rel(oLiyCOrWiJ4p4jQxIr1F, MzZVLTUQ74KbySVwdHfZ, "Store Offers" )
' CONNECTION : [Accesses API implementations] [heuHGHPQyPiOSCrreA29] [OmsC5XSTv64h2ua9yNDK] [outgoing]
Rel(heuHGHPQyPiOSCrreA29, OmsC5XSTv64h2ua9yNDK, "Accesses API implementations" )
' CONNECTION : [Analyse Commercial Data] [uFk6F6ZcKKvnkVRkCNgH] [f1fiXJziytRGVe7hFuLo] [outgoing]
Rel(uFk6F6ZcKKvnkVRkCNgH, f1fiXJziytRGVe7hFuLo, "Analyse Commercial Data" )
' CONNECTION : [Visualize Cache] [LOCysP2vMe5DXLAHEYdU] [mtyHirRmDImFDmca6URg] [outgoing]
Rel(LOCysP2vMe5DXLAHEYdU, mtyHirRmDImFDmca6URg, "Visualize Cache" )
' CONNECTION : [Deployed as] [6uyz5GXgHFSVjrwIwRKC] [4teQrlbMUj5LLqxdVcPK] [outgoing]
Rel(6uyz5GXgHFSVjrwIwRKC, 4teQrlbMUj5LLqxdVcPK, "Deployed as" )
' CONNECTION : [Deploy] [F2hUPV68esNdYOZlEDZp] [OmsC5XSTv64h2ua9yNDK] [outgoing]
Rel(F2hUPV68esNdYOZlEDZp, OmsC5XSTv64h2ua9yNDK, "Deploy" )
' CONNECTION : [Retrieve Cache] [MzZVLTUQ74KbySVwdHfZ] [BxsQud7gKwTvBJQ0KNj2] [outgoing]
Rel(MzZVLTUQ74KbySVwdHfZ, BxsQud7gKwTvBJQ0KNj2, "Retrieve Cache" )
' CONNECTION : [Flow] [MoA8eTudOD7sWkzZF9av] [oLiyCOrWiJ4p4jQxIr1F] [outgoing]
Rel(MoA8eTudOD7sWkzZF9av, oLiyCOrWiJ4p4jQxIr1F, "Flow" )
' CONNECTION : [Deploy] [F2hUPV68esNdYOZlEDZp] [BxsQud7gKwTvBJQ0KNj2] [outgoing]
Rel(F2hUPV68esNdYOZlEDZp, BxsQud7gKwTvBJQ0KNj2, "Deploy" )
' CONNECTION : [Delete Cache Records] [hQNUt4ZkKRpf1tU4WmD7] [MzZVLTUQ74KbySVwdHfZ] [outgoing]
Rel(hQNUt4ZkKRpf1tU4WmD7, MzZVLTUQ74KbySVwdHfZ, "Delete Cache Records" )


@enduml
