@startuml
'https://plantuml.com/class-diagram
' CONVERT ICEPANEL DIAGRAM ===========
' Converter          : it.brunasti.icepanel.tools.IcePanelToPlantUmlConverter
' IcePanel JSON File : [./examples/sg/sg-001.json]
' Configuration      : [./examples/sg/config.json]
' Generated at       : Wed Apr 17 16:27:46 CEST 2024

!include https://raw.githubusercontent.com/plantuml-stdlib/C4-PlantUML/master/C4_Context.puml
!include https://raw.githubusercontent.com/plantuml-stdlib/C4-PlantUML/master/C4_Component.puml



Component(BNfOC7foqk1s1ibyQ05W, "Ubuntu Test VM", "") { 
    ' CLASSES =======
    Container(kmbDI3cUwBYgzZCyulAH, "Visula Studio Code", "", "")
    Container(j57mi6bn5IBAPBBcqa2b, "Local File System", "", "")
    Container(FMEFRLGEAtEaY3KE4ZT3, "Cypress Engine", "", "")
}


' NEIGHBOR CLASSES =======
ContainerDb(UWeoMC7K0ntstoLn4FBh, "Git Repository", "", "")
Component(Kl9tTaoCuXqdHTvo4lkZ, "Signavio BPM Connector", "")
Component(QkIAEDVBPA2TLsAXXWO2, "Test SAP SolMan 7.2", "")
Component(42e8Z1KIHKsxaWdqk3nq, "Test Signavio BPM", "")


' CONNECTIONS =======
Rel(FMEFRLGEAtEaY3KE4ZT3, Kl9tTaoCuXqdHTvo4lkZ, "Execute Tests" )
Rel(UWeoMC7K0ntstoLn4FBh, j57mi6bn5IBAPBBcqa2b, "Push/Pull" )
Rel(j57mi6bn5IBAPBBcqa2b, UWeoMC7K0ntstoLn4FBh, "Return of Push/Pull" )
Rel(kmbDI3cUwBYgzZCyulAH, FMEFRLGEAtEaY3KE4ZT3, "Run" )
Rel(kmbDI3cUwBYgzZCyulAH, j57mi6bn5IBAPBBcqa2b, "Access" )
Rel(FMEFRLGEAtEaY3KE4ZT3, j57mi6bn5IBAPBBcqa2b, "Read Tests" )
Rel(kmbDI3cUwBYgzZCyulAH, UWeoMC7K0ntstoLn4FBh, "Access" )
Rel(FMEFRLGEAtEaY3KE4ZT3, QkIAEDVBPA2TLsAXXWO2, "Setup Test Data" )
Rel(FMEFRLGEAtEaY3KE4ZT3, 42e8Z1KIHKsxaWdqk3nq, "Setup Test Data" )


@enduml
