@startuml
'https://plantuml.com/class-diagram
' CONVERT ICEPANEL DIAGRAM ===========
' Converter          : it.brunasti.icepanel.tools.IcePanelToPlantUMLConverter
' IcePanel JSON File : [./examples/sg/sg-001.json]
' Configuration      : [./examples/sg/config.json]
' Generated at       : Fri Apr 05 18:30:42 CEST 2024

!include https://raw.githubusercontent.com/plantuml-stdlib/C4-PlantUML/master/C4_Context.puml
!include https://raw.githubusercontent.com/plantuml-stdlib/C4-PlantUML/master/C4_Component.puml



System_Boundary(z8HfnmEu1FwVBLuoFTXM, "Subscriber Account (Customer)" ) {
    ' CLASSES =======
    Component(UDzF9znNIXtFk9LwBDHM, "Destination Service", "" )
    Component(3TXGCv2PXpssXY07gX0S, "User Authentication (XSUAA)", "" )
}


' NEIGHBOR CLASSES =======
Component(Kl9tTaoCuXqdHTvo4lkZ, "Signavio BPM Connector", "" )
Component(42e8Z1KIHKsxaWdqk3nq, "Test Signavio BPM", "" )
Component(OHrd5OnZcC3om9jIhGs3, "SCC - SAP Cloud Connector", "" )


' CONNECTIONS =======
Rel(UDzF9znNIXtFk9LwBDHM, 42e8Z1KIHKsxaWdqk3nq, "HTTPS / Basic" )
Rel(42e8Z1KIHKsxaWdqk3nq, UDzF9znNIXtFk9LwBDHM, "Return of HTTPS / Basic" )
Rel(Kl9tTaoCuXqdHTvo4lkZ, UDzF9znNIXtFk9LwBDHM, "Trusted Call" )
Rel(UDzF9znNIXtFk9LwBDHM, Kl9tTaoCuXqdHTvo4lkZ, "Return of Trusted Call" )
Rel(UDzF9znNIXtFk9LwBDHM, OHrd5OnZcC3om9jIhGs3, "Secure VPN tunnel" )


@enduml
