@startuml
'https://plantuml.com/class-diagram
' CONVERT ICEPANEL DIAGRAM ===========
' Converter          : it.brunasti.icepanel.tools.IcePanelToPlantUmlConverter
' IcePanel JSON File : [./examples/tadaah/tadaah-001.json]
' Configuration      : [./examples/tadaah/config.json]
' Generated at       : Fri Jan 10 17:22:14 CET 2025

!include https://raw.githubusercontent.com/plantuml-stdlib/C4-PlantUML/master/C4_Context.puml
!include https://raw.githubusercontent.com/plantuml-stdlib/C4-PlantUML/master/C4_Component.puml



ContainerDb(7GHp8F8aCdHY91UqUPRd, "Tadaah Database", "") { 
    ' CLASSES =======
    Container(0tsl8NoqQthetjG1IfCY, "Payment DB", "", "")
    Container(K7gvMXFEhBLyFvU9emlk, "User DB", "", "")
    Container(iHxJuDcOScVk3PbjBcJm, "Notification DB", "", "")
    Container(AtImPU6py93rBswwEwtO, "Invoice DB", "", "")
    Container(XaKbISuZOfRaAYbo9UM9, "Hiring DB", "", "")
    Container(uzTJfXJ4WIOTbEyYvR2M, "Document DB", "", "")
}


' NEIGHBOR CLASSES =======
Container(jXlbjUjjr2WB6pexPMxU, "Invoice microservice", "", "")
Container(E7di0Acs7tcqBfqOKmWa, "Documents microservice", "", "")
Container(OJhfZ67lBSzo6O8q5N5D, "Hiring microservice", "", "")
Container(xujXNZvKo0NhWwHHnzNi, "Payment microservice", "", "")
Container(OW3XMbiGuD47ot1uwmK9, "Users and Organisations microservice", "", "")
Container(xNzhCu9TkahbVVVwZMa7, "Notification microservice", "", "")


' SUB DIAGRAM CONNECTIONS ======= Base : [7GHp8F8aCdHY91UqUPRd]
' CONNECTION : [Sends data to] [xujXNZvKo0NhWwHHnzNi] [0tsl8NoqQthetjG1IfCY] [outgoing]
Rel(xujXNZvKo0NhWwHHnzNi, 0tsl8NoqQthetjG1IfCY, "Sends data to" )
' CONNECTION : [Exchange Data (4t)] [XaKbISuZOfRaAYbo9UM9] [uzTJfXJ4WIOTbEyYvR2M] [bidirectional]
Rel(XaKbISuZOfRaAYbo9UM9, uzTJfXJ4WIOTbEyYvR2M, "Exchange Data (4t)" )
Rel(uzTJfXJ4WIOTbEyYvR2M, XaKbISuZOfRaAYbo9UM9, "Return of Exchange Data (4t)" )
' CONNECTION : [Exchange Data (2t)] [iHxJuDcOScVk3PbjBcJm] [0tsl8NoqQthetjG1IfCY] [bidirectional]
Rel(iHxJuDcOScVk3PbjBcJm, 0tsl8NoqQthetjG1IfCY, "Exchange Data (2t)" )
Rel(0tsl8NoqQthetjG1IfCY, iHxJuDcOScVk3PbjBcJm, "Return of Exchange Data (2t)" )
' CONNECTION : [Sends data to] [E7di0Acs7tcqBfqOKmWa] [uzTJfXJ4WIOTbEyYvR2M] [outgoing]
Rel(E7di0Acs7tcqBfqOKmWa, uzTJfXJ4WIOTbEyYvR2M, "Sends data to" )
' CONNECTION : [Exchange Data (1t)] [uzTJfXJ4WIOTbEyYvR2M] [K7gvMXFEhBLyFvU9emlk] [outgoing]
Rel(uzTJfXJ4WIOTbEyYvR2M, K7gvMXFEhBLyFvU9emlk, "Exchange Data (1t)" )
' CONNECTION : [Exchange Data (2t)] [uzTJfXJ4WIOTbEyYvR2M] [0tsl8NoqQthetjG1IfCY] [bidirectional]
Rel(uzTJfXJ4WIOTbEyYvR2M, 0tsl8NoqQthetjG1IfCY, "Exchange Data (2t)" )
Rel(0tsl8NoqQthetjG1IfCY, uzTJfXJ4WIOTbEyYvR2M, "Return of Exchange Data (2t)" )
' CONNECTION : [Exchange Data (3t)] [AtImPU6py93rBswwEwtO] [K7gvMXFEhBLyFvU9emlk] [bidirectional]
Rel(AtImPU6py93rBswwEwtO, K7gvMXFEhBLyFvU9emlk, "Exchange Data (3t)" )
Rel(K7gvMXFEhBLyFvU9emlk, AtImPU6py93rBswwEwtO, "Return of Exchange Data (3t)" )
' CONNECTION : [Exchange Data (3t)] [XaKbISuZOfRaAYbo9UM9] [AtImPU6py93rBswwEwtO] [bidirectional]
Rel(XaKbISuZOfRaAYbo9UM9, AtImPU6py93rBswwEwtO, "Exchange Data (3t)" )
Rel(AtImPU6py93rBswwEwtO, XaKbISuZOfRaAYbo9UM9, "Return of Exchange Data (3t)" )
' CONNECTION : [Exchange Data (4t)] [XaKbISuZOfRaAYbo9UM9] [0tsl8NoqQthetjG1IfCY] [bidirectional]
Rel(XaKbISuZOfRaAYbo9UM9, 0tsl8NoqQthetjG1IfCY, "Exchange Data (4t)" )
Rel(0tsl8NoqQthetjG1IfCY, XaKbISuZOfRaAYbo9UM9, "Return of Exchange Data (4t)" )
' CONNECTION : [Sends data to] [OW3XMbiGuD47ot1uwmK9] [K7gvMXFEhBLyFvU9emlk] [outgoing]
Rel(OW3XMbiGuD47ot1uwmK9, K7gvMXFEhBLyFvU9emlk, "Sends data to" )
' CONNECTION : [Sends data to] [jXlbjUjjr2WB6pexPMxU] [AtImPU6py93rBswwEwtO] [outgoing]
Rel(jXlbjUjjr2WB6pexPMxU, AtImPU6py93rBswwEwtO, "Sends data to" )
' CONNECTION : [Exchange Data (4t)] [K7gvMXFEhBLyFvU9emlk] [XaKbISuZOfRaAYbo9UM9] [bidirectional]
Rel(K7gvMXFEhBLyFvU9emlk, XaKbISuZOfRaAYbo9UM9, "Exchange Data (4t)" )
Rel(XaKbISuZOfRaAYbo9UM9, K7gvMXFEhBLyFvU9emlk, "Return of Exchange Data (4t)" )
' CONNECTION : [Sands data to] [OJhfZ67lBSzo6O8q5N5D] [XaKbISuZOfRaAYbo9UM9] [outgoing]
Rel(OJhfZ67lBSzo6O8q5N5D, XaKbISuZOfRaAYbo9UM9, "Sands data to" )
' CONNECTION : [Sends data to] [xNzhCu9TkahbVVVwZMa7] [iHxJuDcOScVk3PbjBcJm] [outgoing]
Rel(xNzhCu9TkahbVVVwZMa7, iHxJuDcOScVk3PbjBcJm, "Sends data to" )
' CONNECTION : [Exchange Data (2t)] [K7gvMXFEhBLyFvU9emlk] [iHxJuDcOScVk3PbjBcJm] [bidirectional]
Rel(K7gvMXFEhBLyFvU9emlk, iHxJuDcOScVk3PbjBcJm, "Exchange Data (2t)" )
Rel(iHxJuDcOScVk3PbjBcJm, K7gvMXFEhBLyFvU9emlk, "Return of Exchange Data (2t)" )
' CONNECTION : [Exchange Data (2t)] [AtImPU6py93rBswwEwtO] [0tsl8NoqQthetjG1IfCY] [bidirectional]
Rel(AtImPU6py93rBswwEwtO, 0tsl8NoqQthetjG1IfCY, "Exchange Data (2t)" )
Rel(0tsl8NoqQthetjG1IfCY, AtImPU6py93rBswwEwtO, "Return of Exchange Data (2t)" )
' CONNECTION : [Exchange Data (1t)] [AtImPU6py93rBswwEwtO] [iHxJuDcOScVk3PbjBcJm] [bidirectional]
Rel(AtImPU6py93rBswwEwtO, iHxJuDcOScVk3PbjBcJm, "Exchange Data (1t)" )
Rel(iHxJuDcOScVk3PbjBcJm, AtImPU6py93rBswwEwtO, "Return of Exchange Data (1t)" )
' CONNECTION : [Exchange Data (1t)] [0tsl8NoqQthetjG1IfCY] [K7gvMXFEhBLyFvU9emlk] [bidirectional]
Rel(0tsl8NoqQthetjG1IfCY, K7gvMXFEhBLyFvU9emlk, "Exchange Data (1t)" )
Rel(K7gvMXFEhBLyFvU9emlk, 0tsl8NoqQthetjG1IfCY, "Return of Exchange Data (1t)" )


@enduml
