@startuml
'https://plantuml.com/class-diagram
' CONVERT ICEPANEL DIAGRAM ===========
' Converter          : it.brunasti.icepanel.tools.IcePanelToPlantUmlConverter
' IcePanel JSON File : [./examples/tadaah/tadaah-001-002.json]
' Configuration      : [./examples/tadaah/config.json]
' Generated at       : Wed Jan 15 11:20:26 CET 2025

!include https://raw.githubusercontent.com/plantuml-stdlib/C4-PlantUML/master/C4_Context.puml
!include https://raw.githubusercontent.com/plantuml-stdlib/C4-PlantUML/master/C4_Component.puml



' CLASSES =======
Container(0tsl8NoqQthetjG1IfCY, "Payment DB", "", "")
Component(7LNJ74mouR5kXwMUd40R, "Business Intelligence and Query System", "")
Container(qx3zLDzD49NjzsGy8GsN, "ebdb", "", "")
Container(7xAFfcMNmb9CCOt7pucC, "Android Tadaah App", "", "")
ContainerDb(Crj6OVjno3V3VzBN9ZV7, "AWS S3", "", "")
Container(PPsKcTiOTIF44We88VOs, "Payment DB Replica", "", "")
System(wo1hNaUSBe6V30cFCgBt, "External Provider", "")
System(Vp5nQO6McVzGhiRfTq4I, "Freelancer Plaza", "")
Container(xujXNZvKo0NhWwHHnzNi, "Payment microservice", "", "")
Component(3RsvDPj9KraF3nNbsUyK, "Freelancer Plaza App", "")
Component(LXvhwDpIAwiWY9cfveXB, "Backend Apps", "")
Container(jXlbjUjjr2WB6pexPMxU, "Invoice microservice", "", "")
Person(meF1nRjud1koeACE8CFO, "Organisation", "")
Container(c3z1CGZZJbpBjd9oZl5S, "Merged DB", "", "")
Person(kI67J5sJZiz7LxjwL6OT, "Tadaah Staff", "")
Container(zIMMYLB32509d1pPM9ef, "Common Lib", "", "")
Container(uto1SdyIZwaqL7wSHRx1, "Document DB Replica", "", "")
Component(2JDmHPAMah1HIF7dqy8m, "Mobile Push Notification Systems", "")
Container(K7gvMXFEhBLyFvU9emlk, "User DB", "", "")
ContainerDb(4RHCmF9wWC54tv94wZha, "Tadaah v1.0", "", "")
Container(ErmSGEFjt3933cjfWsae, "Notification DB Replica", "", "")
Container(jH3vKLGq8d8InYPs9p4N, "Invoice DB Replica", "", "")
Component(wiZgyeKZbmqMpX3umth7, "Mobile App", "")
Container(E7di0Acs7tcqBfqOKmWa, "Documents microservice", "", "")
System(JREgvfBWamzpvx8zxFaX, "DataLake", "")
Container(Dqntl7RMPixIOoFKX33z, "User DB Replica", "", "")
Container(OJhfZ67lBSzo6O8q5N5D, "Hiring microservice", "", "")
Container(iHxJuDcOScVk3PbjBcJm, "Notification DB", "", "")
Component(01MRBoO6TNPt4PmaELoO, "Web App", "")
Container(AtImPU6py93rBswwEwtO, "Invoice DB", "", "")
Container(7lmp7OCxUWqGy1ea1Qt5, "lrk-integration DB", "", "")
ContainerDb(8ZpwPsZtb62cdjIqZY9l, "Datalake DB", "", "")
Container(xNzhCu9TkahbVVVwZMa7, "Notification microservice", "", "")
Container(XaKbISuZOfRaAYbo9UM9, "Hiring DB", "", "")
ContainerDb(0slVBZ5IRX5EQzGwSluA, "Freelancer Plaza DB", "", "")
System(VZo4IA6ttTp0XCmX1h6o, "Tadaa System", "A brief description of your system")
Container(VNmHaS6AUVW37Ia1oIKo, "Auth Proxy", "", "")
Person(HSHxou6PlnzMBfem3vDF, "Marketing", "")
Container(TMgxrOsSCJOKTsB4vDlx, "Hiring DB Replica", "", "")
Container(og7u5YsEYstGrVnlMGnr, "iOS Tadaah App", "", "")
Person(ye2OoAgJhthRThhjIe69, "Freelancer", "")
Component(lBh7KhgVrh9fCPMlt1PE, "Oauth Service", "")
ContainerDb(7GHp8F8aCdHY91UqUPRd, "Tadaah v2.0 Database", "", "")
Component(TUJ4gE8Z8W1QkQOuPH4W, "EMail Server", "")
Container(uzTJfXJ4WIOTbEyYvR2M, "Document DB", "", "")
Container(OW3XMbiGuD47ot1uwmK9, "Users and Organisations microservice", "", "")


' CONNECTIONS =======
Rel(iHxJuDcOScVk3PbjBcJm, 0tsl8NoqQthetjG1IfCY, "Exchange Data (2t)" )
Rel(0tsl8NoqQthetjG1IfCY, iHxJuDcOScVk3PbjBcJm, "Return of Exchange Data (2t)" )
Rel(OW3XMbiGuD47ot1uwmK9, VNmHaS6AUVW37Ia1oIKo, "Authenticate" )
Rel(VZo4IA6ttTp0XCmX1h6o, wo1hNaUSBe6V30cFCgBt, "Leverage" )
Rel(xNzhCu9TkahbVVVwZMa7, 2JDmHPAMah1HIF7dqy8m, "Push" )
Rel(XaKbISuZOfRaAYbo9UM9, TMgxrOsSCJOKTsB4vDlx, "Replicated into" )
Rel(jH3vKLGq8d8InYPs9p4N, c3z1CGZZJbpBjd9oZl5S, "Merge into" )
Rel(E7di0Acs7tcqBfqOKmWa, xNzhCu9TkahbVVVwZMa7, "Uses Service" )
Rel(K7gvMXFEhBLyFvU9emlk, Dqntl7RMPixIOoFKX33z, "Replicated into" )
Rel(AtImPU6py93rBswwEwtO, K7gvMXFEhBLyFvU9emlk, "Exchange Data (3t)" )
Rel(K7gvMXFEhBLyFvU9emlk, AtImPU6py93rBswwEwtO, "Return of Exchange Data (3t)" )
Rel(HSHxou6PlnzMBfem3vDF, 7LNJ74mouR5kXwMUd40R, "Analyse Data" )
Rel(kI67J5sJZiz7LxjwL6OT, Vp5nQO6McVzGhiRfTq4I, "Uses" )
Rel(ye2OoAgJhthRThhjIe69, og7u5YsEYstGrVnlMGnr, "Uses" )
Rel(meF1nRjud1koeACE8CFO, Vp5nQO6McVzGhiRfTq4I, "Uses" )
Rel(OW3XMbiGuD47ot1uwmK9, K7gvMXFEhBLyFvU9emlk, "Sends data to" )
Rel(jXlbjUjjr2WB6pexPMxU, AtImPU6py93rBswwEwtO, "Sends data to" )
Rel(OJhfZ67lBSzo6O8q5N5D, XaKbISuZOfRaAYbo9UM9, "Sands data to" )
Rel(xNzhCu9TkahbVVVwZMa7, iHxJuDcOScVk3PbjBcJm, "Sends data to" )
Rel(kI67J5sJZiz7LxjwL6OT, 7LNJ74mouR5kXwMUd40R, "Access Data" )
Rel(OJhfZ67lBSzo6O8q5N5D, xNzhCu9TkahbVVVwZMa7, "Uses Service" )
Rel(PPsKcTiOTIF44We88VOs, c3z1CGZZJbpBjd9oZl5S, "Merge into" )
Rel(AtImPU6py93rBswwEwtO, jH3vKLGq8d8InYPs9p4N, "Replicated into" )
Rel(AtImPU6py93rBswwEwtO, 0tsl8NoqQthetjG1IfCY, "Exchange Data (2t)" )
Rel(0tsl8NoqQthetjG1IfCY, AtImPU6py93rBswwEwtO, "Return of Exchange Data (2t)" )
Rel(meF1nRjud1koeACE8CFO, 01MRBoO6TNPt4PmaELoO, "Uses" )
Rel(OW3XMbiGuD47ot1uwmK9, xNzhCu9TkahbVVVwZMa7, "Uses Service" )
Rel(AtImPU6py93rBswwEwtO, iHxJuDcOScVk3PbjBcJm, "Exchange Data (1t)" )
Rel(iHxJuDcOScVk3PbjBcJm, AtImPU6py93rBswwEwtO, "Return of Exchange Data (1t)" )
Rel(0tsl8NoqQthetjG1IfCY, K7gvMXFEhBLyFvU9emlk, "Exchange Data (1t)" )
Rel(K7gvMXFEhBLyFvU9emlk, 0tsl8NoqQthetjG1IfCY, "Return of Exchange Data (1t)" )
Rel(OW3XMbiGuD47ot1uwmK9, OJhfZ67lBSzo6O8q5N5D, "Uses Service" )
Rel(xujXNZvKo0NhWwHHnzNi, 0tsl8NoqQthetjG1IfCY, "Sends data to" )
Rel(XaKbISuZOfRaAYbo9UM9, uzTJfXJ4WIOTbEyYvR2M, "Exchange Data (4t)" )
Rel(uzTJfXJ4WIOTbEyYvR2M, XaKbISuZOfRaAYbo9UM9, "Return of Exchange Data (4t)" )
Rel(uto1SdyIZwaqL7wSHRx1, c3z1CGZZJbpBjd9oZl5S, "Merge into" )
Rel(E7di0Acs7tcqBfqOKmWa, uzTJfXJ4WIOTbEyYvR2M, "Sends data to" )
Rel(ye2OoAgJhthRThhjIe69, 7xAFfcMNmb9CCOt7pucC, "Uses" )
Rel(jXlbjUjjr2WB6pexPMxU, xNzhCu9TkahbVVVwZMa7, "Uses Service" )
Rel(iHxJuDcOScVk3PbjBcJm, ErmSGEFjt3933cjfWsae, "Replicated into" )
Rel(Dqntl7RMPixIOoFKX33z, c3z1CGZZJbpBjd9oZl5S, "Merge into" )
Rel(TMgxrOsSCJOKTsB4vDlx, c3z1CGZZJbpBjd9oZl5S, "Merge into" )
Rel(3RsvDPj9KraF3nNbsUyK, 0slVBZ5IRX5EQzGwSluA, "CRUD" )
Rel(uzTJfXJ4WIOTbEyYvR2M, K7gvMXFEhBLyFvU9emlk, "Exchange Data (1t)" )
Rel(uzTJfXJ4WIOTbEyYvR2M, 0tsl8NoqQthetjG1IfCY, "Exchange Data (2t)" )
Rel(0tsl8NoqQthetjG1IfCY, uzTJfXJ4WIOTbEyYvR2M, "Return of Exchange Data (2t)" )
Rel(Vp5nQO6McVzGhiRfTq4I, JREgvfBWamzpvx8zxFaX, "Replicate" )
Rel(xujXNZvKo0NhWwHHnzNi, xNzhCu9TkahbVVVwZMa7, "Uses Service" )
Rel(XaKbISuZOfRaAYbo9UM9, AtImPU6py93rBswwEwtO, "Exchange Data (3t)" )
Rel(AtImPU6py93rBswwEwtO, XaKbISuZOfRaAYbo9UM9, "Return of Exchange Data (3t)" )
Rel(XaKbISuZOfRaAYbo9UM9, 0tsl8NoqQthetjG1IfCY, "Exchange Data (4t)" )
Rel(0tsl8NoqQthetjG1IfCY, XaKbISuZOfRaAYbo9UM9, "Return of Exchange Data (4t)" )
Rel(xNzhCu9TkahbVVVwZMa7, TUJ4gE8Z8W1QkQOuPH4W, "Send eMail" )
Rel(kI67J5sJZiz7LxjwL6OT, 01MRBoO6TNPt4PmaELoO, "Uses" )
Rel(ye2OoAgJhthRThhjIe69, Vp5nQO6McVzGhiRfTq4I, "Uses" )
Rel(ErmSGEFjt3933cjfWsae, c3z1CGZZJbpBjd9oZl5S, "Merge into" )
Rel(01MRBoO6TNPt4PmaELoO, LXvhwDpIAwiWY9cfveXB, "Access Endpoints" )
Rel(K7gvMXFEhBLyFvU9emlk, XaKbISuZOfRaAYbo9UM9, "Exchange Data (4t)" )
Rel(XaKbISuZOfRaAYbo9UM9, K7gvMXFEhBLyFvU9emlk, "Return of Exchange Data (4t)" )
Rel(7LNJ74mouR5kXwMUd40R, c3z1CGZZJbpBjd9oZl5S, "Read" )
Rel(E7di0Acs7tcqBfqOKmWa, OJhfZ67lBSzo6O8q5N5D, "Uses Service" )
Rel(0tsl8NoqQthetjG1IfCY, PPsKcTiOTIF44We88VOs, "Replicated into" )
Rel(K7gvMXFEhBLyFvU9emlk, iHxJuDcOScVk3PbjBcJm, "Exchange Data (2t)" )
Rel(iHxJuDcOScVk3PbjBcJm, K7gvMXFEhBLyFvU9emlk, "Return of Exchange Data (2t)" )
Rel(E7di0Acs7tcqBfqOKmWa, Crj6OVjno3V3VzBN9ZV7, "Store Document" )
Rel(wiZgyeKZbmqMpX3umth7, LXvhwDpIAwiWY9cfveXB, "Access Endpoints" )
Rel(uzTJfXJ4WIOTbEyYvR2M, uto1SdyIZwaqL7wSHRx1, "Replicated into" )
Rel(VNmHaS6AUVW37Ia1oIKo, lBh7KhgVrh9fCPMlt1PE, "Validate auth" )


' PARENT CONNECTIONS =======
  7GHp8F8aCdHY91UqUPRd <.. 0tsl8NoqQthetjG1IfCY 
  VZo4IA6ttTp0XCmX1h6o <.. 0tsl8NoqQthetjG1IfCY 
  ZrO7EKBJrWX4yzMUQE7L <.. 0tsl8NoqQthetjG1IfCY 
  JREgvfBWamzpvx8zxFaX <.. 7LNJ74mouR5kXwMUd40R 
  4RHCmF9wWC54tv94wZha <.. qx3zLDzD49NjzsGy8GsN 
  VZo4IA6ttTp0XCmX1h6o <.. qx3zLDzD49NjzsGy8GsN 
  ZrO7EKBJrWX4yzMUQE7L <.. qx3zLDzD49NjzsGy8GsN 
  wiZgyeKZbmqMpX3umth7 <.. 7xAFfcMNmb9CCOt7pucC 
  VZo4IA6ttTp0XCmX1h6o <.. 7xAFfcMNmb9CCOt7pucC 
  ZrO7EKBJrWX4yzMUQE7L <.. 7xAFfcMNmb9CCOt7pucC 
  VZo4IA6ttTp0XCmX1h6o <.. Crj6OVjno3V3VzBN9ZV7 
  ZrO7EKBJrWX4yzMUQE7L <.. Crj6OVjno3V3VzBN9ZV7 
  8ZpwPsZtb62cdjIqZY9l <.. PPsKcTiOTIF44We88VOs 
  JREgvfBWamzpvx8zxFaX <.. PPsKcTiOTIF44We88VOs 
  ZrO7EKBJrWX4yzMUQE7L <.. wo1hNaUSBe6V30cFCgBt 
  LXvhwDpIAwiWY9cfveXB <.. xujXNZvKo0NhWwHHnzNi 
  VZo4IA6ttTp0XCmX1h6o <.. xujXNZvKo0NhWwHHnzNi 
  ZrO7EKBJrWX4yzMUQE7L <.. xujXNZvKo0NhWwHHnzNi 
  Vp5nQO6McVzGhiRfTq4I <.. 3RsvDPj9KraF3nNbsUyK 
  VZo4IA6ttTp0XCmX1h6o <.. LXvhwDpIAwiWY9cfveXB 
  ZrO7EKBJrWX4yzMUQE7L <.. LXvhwDpIAwiWY9cfveXB 
  LXvhwDpIAwiWY9cfveXB <.. jXlbjUjjr2WB6pexPMxU 
  VZo4IA6ttTp0XCmX1h6o <.. jXlbjUjjr2WB6pexPMxU 
  ZrO7EKBJrWX4yzMUQE7L <.. jXlbjUjjr2WB6pexPMxU 
  ZrO7EKBJrWX4yzMUQE7L <.. meF1nRjud1koeACE8CFO 
  8ZpwPsZtb62cdjIqZY9l <.. c3z1CGZZJbpBjd9oZl5S 
  JREgvfBWamzpvx8zxFaX <.. c3z1CGZZJbpBjd9oZl5S 
  ZrO7EKBJrWX4yzMUQE7L <.. kI67J5sJZiz7LxjwL6OT 
  LXvhwDpIAwiWY9cfveXB <.. zIMMYLB32509d1pPM9ef 
  VZo4IA6ttTp0XCmX1h6o <.. zIMMYLB32509d1pPM9ef 
  ZrO7EKBJrWX4yzMUQE7L <.. zIMMYLB32509d1pPM9ef 
  8ZpwPsZtb62cdjIqZY9l <.. uto1SdyIZwaqL7wSHRx1 
  JREgvfBWamzpvx8zxFaX <.. uto1SdyIZwaqL7wSHRx1 
  wo1hNaUSBe6V30cFCgBt <.. 2JDmHPAMah1HIF7dqy8m 
  ZrO7EKBJrWX4yzMUQE7L <.. 2JDmHPAMah1HIF7dqy8m 
  7GHp8F8aCdHY91UqUPRd <.. K7gvMXFEhBLyFvU9emlk 
  VZo4IA6ttTp0XCmX1h6o <.. K7gvMXFEhBLyFvU9emlk 
  ZrO7EKBJrWX4yzMUQE7L <.. K7gvMXFEhBLyFvU9emlk 
  VZo4IA6ttTp0XCmX1h6o <.. 4RHCmF9wWC54tv94wZha 
  ZrO7EKBJrWX4yzMUQE7L <.. 4RHCmF9wWC54tv94wZha 
  8ZpwPsZtb62cdjIqZY9l <.. ErmSGEFjt3933cjfWsae 
  JREgvfBWamzpvx8zxFaX <.. ErmSGEFjt3933cjfWsae 
  8ZpwPsZtb62cdjIqZY9l <.. jH3vKLGq8d8InYPs9p4N 
  JREgvfBWamzpvx8zxFaX <.. jH3vKLGq8d8InYPs9p4N 
  VZo4IA6ttTp0XCmX1h6o <.. wiZgyeKZbmqMpX3umth7 
  ZrO7EKBJrWX4yzMUQE7L <.. wiZgyeKZbmqMpX3umth7 
  LXvhwDpIAwiWY9cfveXB <.. E7di0Acs7tcqBfqOKmWa 
  VZo4IA6ttTp0XCmX1h6o <.. E7di0Acs7tcqBfqOKmWa 
  ZrO7EKBJrWX4yzMUQE7L <.. E7di0Acs7tcqBfqOKmWa 
  8ZpwPsZtb62cdjIqZY9l <.. Dqntl7RMPixIOoFKX33z 
  JREgvfBWamzpvx8zxFaX <.. Dqntl7RMPixIOoFKX33z 
  LXvhwDpIAwiWY9cfveXB <.. OJhfZ67lBSzo6O8q5N5D 
  VZo4IA6ttTp0XCmX1h6o <.. OJhfZ67lBSzo6O8q5N5D 
  ZrO7EKBJrWX4yzMUQE7L <.. OJhfZ67lBSzo6O8q5N5D 
  7GHp8F8aCdHY91UqUPRd <.. iHxJuDcOScVk3PbjBcJm 
  VZo4IA6ttTp0XCmX1h6o <.. iHxJuDcOScVk3PbjBcJm 
  ZrO7EKBJrWX4yzMUQE7L <.. iHxJuDcOScVk3PbjBcJm 
  VZo4IA6ttTp0XCmX1h6o <.. 01MRBoO6TNPt4PmaELoO 
  ZrO7EKBJrWX4yzMUQE7L <.. 01MRBoO6TNPt4PmaELoO 
  7GHp8F8aCdHY91UqUPRd <.. AtImPU6py93rBswwEwtO 
  VZo4IA6ttTp0XCmX1h6o <.. AtImPU6py93rBswwEwtO 
  ZrO7EKBJrWX4yzMUQE7L <.. AtImPU6py93rBswwEwtO 
  7GHp8F8aCdHY91UqUPRd <.. 7lmp7OCxUWqGy1ea1Qt5 
  VZo4IA6ttTp0XCmX1h6o <.. 7lmp7OCxUWqGy1ea1Qt5 
  ZrO7EKBJrWX4yzMUQE7L <.. 7lmp7OCxUWqGy1ea1Qt5 
  JREgvfBWamzpvx8zxFaX <.. 8ZpwPsZtb62cdjIqZY9l 
  LXvhwDpIAwiWY9cfveXB <.. xNzhCu9TkahbVVVwZMa7 
  VZo4IA6ttTp0XCmX1h6o <.. xNzhCu9TkahbVVVwZMa7 
  ZrO7EKBJrWX4yzMUQE7L <.. xNzhCu9TkahbVVVwZMa7 
  7GHp8F8aCdHY91UqUPRd <.. XaKbISuZOfRaAYbo9UM9 
  VZo4IA6ttTp0XCmX1h6o <.. XaKbISuZOfRaAYbo9UM9 
  ZrO7EKBJrWX4yzMUQE7L <.. XaKbISuZOfRaAYbo9UM9 
  Vp5nQO6McVzGhiRfTq4I <.. 0slVBZ5IRX5EQzGwSluA 
  ZrO7EKBJrWX4yzMUQE7L <.. VZo4IA6ttTp0XCmX1h6o 
  LXvhwDpIAwiWY9cfveXB <.. VNmHaS6AUVW37Ia1oIKo 
  VZo4IA6ttTp0XCmX1h6o <.. VNmHaS6AUVW37Ia1oIKo 
  ZrO7EKBJrWX4yzMUQE7L <.. VNmHaS6AUVW37Ia1oIKo 
  ZrO7EKBJrWX4yzMUQE7L <.. HSHxou6PlnzMBfem3vDF 
  8ZpwPsZtb62cdjIqZY9l <.. TMgxrOsSCJOKTsB4vDlx 
  JREgvfBWamzpvx8zxFaX <.. TMgxrOsSCJOKTsB4vDlx 
  wiZgyeKZbmqMpX3umth7 <.. og7u5YsEYstGrVnlMGnr 
  VZo4IA6ttTp0XCmX1h6o <.. og7u5YsEYstGrVnlMGnr 
  ZrO7EKBJrWX4yzMUQE7L <.. og7u5YsEYstGrVnlMGnr 
  ZrO7EKBJrWX4yzMUQE7L <.. ye2OoAgJhthRThhjIe69 
  wo1hNaUSBe6V30cFCgBt <.. lBh7KhgVrh9fCPMlt1PE 
  ZrO7EKBJrWX4yzMUQE7L <.. lBh7KhgVrh9fCPMlt1PE 
  VZo4IA6ttTp0XCmX1h6o <.. 7GHp8F8aCdHY91UqUPRd 
  ZrO7EKBJrWX4yzMUQE7L <.. 7GHp8F8aCdHY91UqUPRd 
  wo1hNaUSBe6V30cFCgBt <.. TUJ4gE8Z8W1QkQOuPH4W 
  ZrO7EKBJrWX4yzMUQE7L <.. TUJ4gE8Z8W1QkQOuPH4W 
  7GHp8F8aCdHY91UqUPRd <.. uzTJfXJ4WIOTbEyYvR2M 
  VZo4IA6ttTp0XCmX1h6o <.. uzTJfXJ4WIOTbEyYvR2M 
  ZrO7EKBJrWX4yzMUQE7L <.. uzTJfXJ4WIOTbEyYvR2M 
  LXvhwDpIAwiWY9cfveXB <.. OW3XMbiGuD47ot1uwmK9 
  VZo4IA6ttTp0XCmX1h6o <.. OW3XMbiGuD47ot1uwmK9 
  ZrO7EKBJrWX4yzMUQE7L <.. OW3XMbiGuD47ot1uwmK9 


@enduml
